meilisearch/documentation

references/documents.md, references/indexes.md, references/stats.md, references/stop_words.md, references/synonyms.md
Referenced to https://github.com/meilisearch/MeiliDB/pull/311
=> Apply changes made on meilidb PR 311 into the documentation

advanced_guides/binary.md, advanced_guides/distinct.md, advanced_guides/keys.md, advanced_guides/ranking.md, advanced_guides/search_parameters.md, advanced_guides/stop_words.md, introduction/quickstart.md, main_concept/search.md, references/documents.md, references/environment.md, references/health.md, references/indexes.md, references/keys.md, references/search.md, references/settings.md, references/stats.md, references/stop_words.md, references/synonyms.md, references/sys-info.md, references/updates.md, references/version.md
Link to [meilisearch/MeiliSearch#355](https://github.com/meilisearch/MeiliSearch/pull/355)
=> Update default binary settings

.vuepress/config.js, advanced_guides/binary.md, getting_started/download.md
@tpayet Could you try and run it before accepting? I feel like your tab plugin isn't working anymore.
=> add download and curl

getting_started/download.md, getting_started/quickstart.md
We should merge this PR when [meilisearch/MeiliSearch#368](https://github.com/meilisearch/MeiliSearch/pull/368) is merged
=> Add APT usage

references/health.md
Related to:
- [this issue](https://github.com/meilisearch/MeiliSearch/issues/379) in MeiliSearch repo.
- [this PR](https://github.com/meilisearch/MeiliSearch/pull/382) in MeiliSearch repo.
=> Update API reference for health routes

references/settings.md
=> added warning for ranking rule in schema

README.md
=> added github link on contribution part of readme

references/documents.md
=> Precise behavior of get_documents route

advanced_guides/asynchronous_updates.md, getting_started/features.md
Sorry, I obviously messed up with the rebase in the previous PR 😕
I took one by one all the previous suggestions (including the changes asked by @Kerollmops that we hadn't taken into account before the merge).
There were some "conflicts" in some sentences, I tried to do my best to merge the both, tell me if it's ok for you :)
=> Fix update terms

.vuepress/config.js, download/README.md, guides/advanced_guides/binary.md
Completely changed the binary guide. It was messy.
=> Binary guide changed on new structure

advanced_guides/stop_words.md, references/stop_words.md
Fixes: meilisearch/MeiliSearch#417
=> Stop-words routes changes and updated some wording

references/documents.md
Fixes: meilisearch/Meilisearch#416
=> Updated delete batch document route name

.vuepress/config.js, .vuepress/theme/components/MeiliSearchBox.vue, .vuepress/theme/components/Navbar.vue, .vuepress/theme/index.js, package.json, yarn.lock
Add 2 components: `MeiliSearchBox` (the search input) and `NavBar`.
`NavBar` component highly based on [the original one from vuepress](https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/theme-default/components/Navbar.vue).
Integration of [docs-searchbar.js ](https://github.com/meilisearch/docs-searchbar.js) package to display a dropdown. Results come from a MeiliSearch instance.
=> Integrate MeiliSearch

guides/README.md, guides/getting_started/README.md
=> Link modifications

guides/advanced_guides/stop_words.md
=> Change stop words guide

.vuepress/config.js, references/accept_new_fields.md, references/settings.md
- Changes in API Ref titles
- Changes in file name
=> Change accept new field api title

guides/main_concepts/indexes.md
=> Changes to fields properties

README.md, guides/main_concepts/documents.md, references/accept_new_fields.md, references/displayed_attributes.md, references/distinct_attribute.md, references/documents.md, references/indexes.md, references/ranking_rules.md, references/search.md, references/searchable_attributes.md, references/settings.md, references/stats.md, references/stop_words.md, references/synonyms.md, references/updates.md, yarn.lock
(I have not added the `on each setting route` at the end of the baner: it's not really accurate because there is also a DELETE route on the global `settings` route.)
=> Fix post v9

references/displayed_attributes.md
replace Get searchable attributes" with "Get displayed attributes" in displayed attributes API reference.
=> fixes small error in displayed attribute reference

resources/comparison_to_alternatives.md
=> Fix links in comparisons page

guides/introduction/quick_start_guide.md, resources/faq.md
MIstakes from my previous PRs (sorry 😇)
=> Fix minor mistakes

resources/faq.md
I didn't add the button at the home page because I'm not really good at well-displaying stuff 😅
=> Add Slack to FAQ

.vuepress/config.js
=> Add slack link to documentation navbar

resources/comparison_to_alternatives.md
=> Correct typos

guides/advanced_guides/installation.md
Removed Heroku part and rephrasing
=> Rephrase advanced installation

index.md
- “reference” would have to be used differently to make perfect sense here. I recommend cutting it, but I could have a go at a rephrasing if it’s a key word.
- “powerful” & “fast” have roughly the same meaning.
- many shortened sentences.
Also I was surprised to not find any mention of Meili being (or aiming to be) embeddable. Isn’t that a key design goal?
=> Simplified index copy

guides/main_concepts/documents.md, guides/main_concepts/indexes.md
Wanted to make explanations more clear
=> Rephrase explanations

.github/workflows/gh-pages-scraping.yml, .vuepress/scraper/config.json
I confirmed with @tpayet, the secrets have been added.
=> Scraper GitHub action

guides/advanced_guides/README.md, guides/introduction/README.md, guides/introduction/quick_start_guide.md, guides/introduction/whats_next.md, guides/main_concepts/relevancy.md
I was reading again all the documentation and found a few mistakes I forgot, oops.
=> A few minor fixes

.vuepress/components/glossary.vue, guides/main_concepts/documents.md, guides/main_concepts/indexes.md, references/displayed_attributes.md, references/distinct_attribute.md, references/searchable_attributes.md
Minor changes again:
* Use `value` instead of `data`
* Alignment of used terms
* Formatting
=> Minor changes

.vuepress/config.js, resources/about_storage.md
Fixes https://github.com/meilisearch/MeiliSearch/issues/591
=> Add a page about storage resource

.eslintrc.js, .vuepress/config.js, .vuepress/scraper/config.json, .vuepress/theme/components/MeiliSearchBox.vue, .vuepress/theme/components/Navbar.vue, guides/advanced_guides/filtering.md, guides/advanced_guides/search_parameters.md, references/search.md
documents the new filtering feature
blocked by https://github.com/meilisearch/MeiliSearch/pull/592
=> documents filtering

guides/advanced_guides/search_parameters.md, references/search.md
documents crop alignment as implemented in https://github.com/meilisearch/MeiliSearch/pull/543
=> documents aligned cropping

guides/advanced_guides/filtering.md, guides/advanced_guides/search_parameters.md
Gives more useful explanations as how to concretely use filters, linking guide to api reference.
=> improves filtering documentation

resources/sdks.md
Hi,
I would like to add the Swift SDK in the list of SDKs.
Is there anything more I should change?
Thank you.
=> Add Swift client in SDKs list

resources/sdks.md
=> Upd SDKs guidelines

guides/advanced_guides/filtering.md
documents the ability to filter on arrays
=> documentation for filtering on arrays

.vuepress/config.js
It's not a draft but DO NOT MERGE BEFORE TALKING TO ME ON SLACK 🙂 -> the GitHub Secrets need to be changed
=> Change credentials for search bar

guides/advanced_guides/faceted_search.md, guides/advanced_guides/search_parameters.md, references/search.md
Small changes to faceted search guide
=> Re-arrange faceting documentation and cleanup examples

guides/advanced_guides/configuration.md, guides/advanced_guides/web_interface.md, guides/main_concepts/documents.md
What is the use case for these two options? @qdequele @Kerollmops
=> Lmdb map size

.gitignore, guides/advanced_guides/field_properties.md, guides/advanced_guides/settings.md, references/displayed_attributes.md, references/searchable_attributes.md
Introduces the difference between new fields and known fields and how they will behave.
Based on this issue: meilisearch/MeiliSearch#761
=> New fields and Known fields

resources/howtos/search_bar_for_docs.md
<s>⚠️ Should not be merged before [this PR](https://github.com/meilisearch/docs-scraper/pull/33).</s> Merge done!
=> Upd search bar for docs article

.github/workflows/gh-pages-scraping.yml
https://hub.docker.com/layers/getmeili/docs-scraper/v0.9.4/images/sha256-65452d7106e6d89c6b8d1c72655ceed4ffb71eafbeeb35892c84a4ab7646bda1?context=repo
=> Bump docs-scraper to v0.9.4

.vuepress/config.js, package.json, yarn.lock
Landing page button `GETTING STARTED` was long to load because images were loaded first.
The gif on the landing page is 7MB. Which makes the loading of that specific button dependent of the loading of the GIF.
With lazy load image loading comes after all other elements and will only load if it appears on the screen of the user.
=> Add lazy load for faster UI loading

.vuepress/config.js, package.json, yarn.lock
=> lazy load images

guides/introduction/quick_start_guide.md, guides/main_concepts/relevancy.md
- Removed installation from getting started (buggy)
- Removed hard-coded examples 
- Replaced them with code-sample plugin
=> Refactor getting started and fix bug

resources/sdks.md
- Update the resources page about SDKs and integration tools with all ready-to-use libraries.
- Sort the SDKs in alphabetic order -> no more jealous 😇
=> Update resources page about SDKs/Integrations

.vuepress/components/ClientGlossary.vue, .vuepress/components/glossary.vue
Add a label prop to the glossary component to be able to change the label and keep the predefined definitions.
=> Add label prop to glossary component

.code-samples.meilisearch.yaml, .github/workflows/gh-pages-scraping.yml, guides/advanced_guides/search_parameters.md, guides/main_concepts/search.md, package.json, references/search.md, resources/sdks.md, yarn.lock
documents https://github.com/meilisearch/MeiliSearch/issues/729
=> documents placeholder search

.vuepress/enhanceApp.js
Redirect `/error` route to `/errors` page
=> Add redirection for errors

.github/workflows/gh-pages-scraping.yml
https://github.com/meilisearch/docs-scraper/releases/tag/v0.10.0
=> Update docs-scraper version

.vuepress/config.js, package.json, yarn.lock
Previously the `note` plugin was removed to remove a bug. 
I forgot to put it back. This is the purpose of this PR
=> Add note plugin

guides/README.md
=> Add introduction to MeiliSearch (#484)

guides/advanced_guides/configuration.md
add documentation for:
* `--snapshot-path`
* `--snapshot-interval-sec`
* `--init-from-snapshot`
* `--recover-from-snapshot`
=> snapshot: add CLI documentation

guides/advanced_guides/settings.md
Remove hardcoded sample from the documentation and replaced it with a code sample id.
fixes: #474
=> Remove hardcoded sample

.vuepress/config.js, guides/advanced_guides/configuration.md
- ~[ ] Tests suite for meilisearch-http: minimal requirements meilisearch/meilisearch#814~
- ~[ ] Avoid sending the entire request in error message when error is 'Payload too large'meilisearch/meilisearch#862~
- ~[ ] Update nbHits count with filtered documents meilisearch/meilisearch#849~
- ~[ ] Uncaught ReferenceError: select is not defined meilisearch/meilisearch#896~
- ~[ ] Fix clippy warnings meilisearch/meilisearch#889~
- ~[ ] Remove schema mention in error message meilisearch/meilisearch#888~
- ~[ ] Cleanup readme meilisearch/meilisearch#828~
- ~[ ] Fixes default values on web interface #874~
=> Prepare documentation for MeiliSearch v0.14

.vuepress/config.js
=> Update fanthom link

guides/advanced_guides/safeguards.md
- Clarify the following flags: 
- `--ignore-missing-snapshot`
- `--ignore-snapshot-if-db-exists`
- Remove mention of `backups`
=> Update snapshot documentation

.vuepress/config.js, guides/advanced_guides/known_limitations.md
=> Add limitations guide

guides/advanced_guides/known_limitations.md
Per my research "Maxime" would technically be English, but pushed me off balance while reading it.
=> Fix small typos in "Known Limitation"

.github/workflows/gh-pages-scraping.yml
https://github.com/meilisearch/docs-scraper/releases/tag/v0.10.2
=> Update docs-scraper version to v0.10.2

guides/advanced_guides/search_parameters.md
=> Fix facetsDistribution

.code-samples.meilisearch.yaml
=> fixes update distinct attribute example

.github/workflows/gh-pages-scraping.yml, guides/advanced_guides/configuration.md, guides/advanced_guides/snapshots_and_dumps.md, references/dump.md
Documentation related to:
- [Consider changing the extension name of dump and snapshot](https://github.com/meilisearch/MeiliSearch/issues/1010)
- [Snapshot redesign](https://github.com/meilisearch/MeiliSearch/issues/1009)
- [Update of the dump status body](https://github.com/meilisearch/MeiliSearch/issues/998)
- [Rename MEILI_DUMPS_FOLDER environment variable](https://github.com/meilisearch/MeiliSearch/issues/988)
=> Snapshot and Dumps redesign

.vuepress/code-samples/sdks.json
Should be merged once https://github.com/meilisearch/meilisearch-rust/pull/40 is merged!
Thanks to @Mubelotix!!! 🚀
=> Add Rust as language in tabs

references/documents.md, references/indexes.md, references/settings.md
Just few more lines on the references part.
=> lazy index doc for references

.code-samples.meilisearch.yaml, references/health.md
- change `GET /health` to constantly return `204 No Content`
- remove ` PUT /health`
=> health route redesign

errors.yaml
Remove maintenance errorCode until it is a possible `errorCode` again.
=> Remove maintenance errorCode

.github/workflows/gh-pages-scraping.yml
https://hub.docker.com/repository/docker/getmeili/docs-scraper
=> Update docs-scraper to v0.10.4

.vuepress/code-samples/client.js, guides/advanced_guides/distinct.md, guides/advanced_guides/faceted_search.md, guides/advanced_guides/field_properties.md, guides/advanced_guides/filtering.md, guides/advanced_guides/search_parameters.md, guides/advanced_guides/settings.md, guides/advanced_guides/snapshots_and_dumps.md, guides/advanced_guides/web_interface.md, guides/introduction/quick_start_guide.md, guides/main_concepts/documents.md, guides/main_concepts/indexes.md, guides/main_concepts/search.md, references/attributes_for_faceting.md, references/displayed_attributes.md, references/distinct_attribute.md, references/documents.md, references/dump.md, references/health.md, references/indexes.md, references/keys.md, references/ranking_rules.md, references/search.md, references/searchable_attributes.md, references/settings.md, references/stats.md, references/stop_words.md, references/synonyms.md, references/updates.md, references/version.md
Fixes non-passing tests in #575 
respect PascalCase naming for vue components.
=> Update code-samples to CodeSamples

references/README.md
Version was not updated in this warning
=> Change version compatibility to 0.16

resources/sdks.md
Instant meilisearch was missing from the SDK's list
=> Add instant meilisearch

.vuepress/public/postman/meilisearch-collection.json
It seems to have a lot of changes, but there are not: it's because I reorganized the orders of different requests. But actually, only the name of the collection changed.
=> Update Postman collection

guides/advanced_guides/configuration.md, guides/advanced_guides/web_interface.md
documents https://github.com/meilisearch/MeiliSearch/pull/1097, according to https://github.com/meilisearch/specifications/blob/master/text/0001-frontend-disable-prod.md
=> Frontend disable

.vuepress/config.js, .vuepress/public/postman/meilisearch-collection.json, guides/advanced_guides/configuration.md, guides/advanced_guides/web_interface.md
=> Prepare MeiliSearch for release 12/2020

errors.yaml
Hey, here the updated error.yaml.
=> Fixes #560

.vuepress/config.js, faq/README.md, guides/introduction/whats_next.md, references/README.md, resources/howtos/README.md
Trying to fix #642 
I was not able to reproduce the bug locally, so I am submitting a draft PR in order to deploy a test branch on Netlify
=> Fix FAQ link in API references homepage

.github/workflows/update-copyright.yml
trying with a manual workflow for test
=> add an action to update the year automatically

guides/main_concepts/documents.md
Small clarifications to a slightly confusing section of documents.md 😁
=> Rephrase payload limit example

.vuepress/config.js, guides/advanced_guides/tokenization.md, index.md
See https://github.com/meilisearch/documentation/issues/675
=> New tokenizer documentation

.code-samples.meilisearch.yaml
Fix code sample for API references update document route (was POST, should be PUT).
=> Fixes add_or_update_documents_1 code sample

.code-samples.meilisearch.yaml, guides/advanced_guides/field_properties.md, guides/advanced_guides/settings.md, references/displayed_attributes.md, references/searchable_attributes.md, references/settings.md
https://github.com/meilisearch/integration-guides/issues/75
=> Update Searchable and Displayed attributes examples

.github/workflows/gh-pages-scraping.yml
=> adjust gh-pages-scraping.yml

resources/howtos/digitalocean_droplet.md
~DO NOT MERGE UNTIL THE OFFICIAL DIGITALOCEAN IMAGE IS PUBLISHED (asked me if doubts)~
Changes to the DigitalOcean how-to
- Use `meilisearch` user to connect, instead of root
- Add health check
- Some spelling :)
=> Update DO how-to v0.18.1

reference/api/synonyms.md, reference/features/settings.md, reference/features/synonyms.md
Add information described in #725 to the reference documentation concerning synonyms.
=> Synonym normalization

reference/features/known_limitations.md, reference/features/search_parameters.md
Add information on 10-word query limit to search_parameters.md#query-q and known_limitations.md
=> Add query limit info

README.md
prevent the horizontal scrollbar for the code
=> split the command in two lines

.vuepress/components/linkButton.vue, index.md
Im not sure how you the bug happened but I think this will fix it?
=> Fix link button

reference/features/README.md, reference/features/language.md
Fix link in language.md, and add language.md to Feature Reference table of contents.
=> Fix link in language.md

learn/tutorials/getting_started.md
make it faster for people wanting to curl it up right away
=> change JSON link to the raw directly

create/how_to/qovery.md
Hi the Meili team,
I added docs on deploying Meilisearch to Qovery - feedback is welcome.
Romaric.
=> support Qovery as a deployment Option

.vuepress/components/RouteHighlighter.vue, .vuepress/components/linkButton.vue, .vuepress/config.js, .vuepress/styles/index.styl, .vuepress/styles/palette.styl
Update colors and font family to match the [landing page](https://www.meilisearch.com/) theme.
- Font family to Inter
- Accent color from `#3eaf7c` to `#0063f7`
- Body background color from `#ffffff` to `#fafafc`
- Body text color from `#2c3e50` to `#000000`
- RouteHighlighter methods:
Get from from `#3eaf7c` to `#39d98a`, source: ![image](https://user-images.githubusercontent.com/7695608/108957339-16fbe400-7650-11eb-823e-5bfe3348e46a.png)
Post from from `#f5a623` to `#fdac42`, source: ![image](https://user-images.githubusercontent.com/7695608/108957386-267b2d00-7650-11eb-99f0-e256b1bcb381.png)
Put from from `#2c88ea` to `#6698ff`, source: ![image](https://user-images.githubusercontent.com/7695608/108957435-3b57c080-7650-11eb-871e-c44b8db1a7b5.png)
Delete from from `#ef5d5a` to `#ff5c5c`, …
=> Match landing page theme

.vuepress/config.js
=> Fixing zoom issue for logo in the navbar

create/faq.md, learn/core_concepts/documents.md
Add information from #721 to the FAQ.
Closes #721
=> Add recommended requirements answer to FAQ

learn/advanced/snapshots_vs_dumps.md
feel free to change the text or even change the text in the menu. The goal is to make it clear for someone who doesn't know what are snapshots or dump.
=> add more generic word to data backup

learn/advanced/asynchronous_updates.md
feel free to reword since you get the gist of what I wanted to achieve
=> change the wording for a smoother word & making it clear it's not a common thing

learn/getting_started/quick_start.md
Merged now because used in the recording of a conference.
=> Force version of instant-search as new version bugs

reference/features/snapshots.md
=> Remove inconsistency in snapshots documentation

.vuepress/config.js
It's what we use instead of Google Analytics
Closes #892
=> add Amplitude tracking

create/how_to/digitalocean_droplet.md
Changed the health in the tutorial of digital ocean from `204` to `200`
=> Update health http code in digital ocean how to

create/how_to/gcp.md
This is the basic guide on how to deploy MeiliSearch on GCP using our own Custom Image.
Thanks for your help @react-learner !
=> Add GCP deployment how-to

create/faq.md
Based on feedback from @qdequele .
=> Improve recommended requirements FAQ answer

create/faq.md
See: https://github.com/meilisearch/documentation/pull/843#discussion_r618478145
=> Remove inaccurate info about RAM limit in new engine

learn/what_is_meilisearch/sdks.md
Following the deprecation of meilisearch-laravel-scout because we are now supported by the official laravel scout repo 🎉
=> Update laravel in integration list

index.md
Remove mention of "beta" and reduce content sprawl.
=> Refresh homepage content

reference/features/search_parameters.md
Related to https://github.com/meilisearch/MeiliSearch/discussions/1380#discussioncomment-792844
@gmourier is aware of this problem, `matche` might be improved in the future
=> Update matches doc

learn/getting_started/quick_start.md
Specify user needs to download movies.json file
=> Update quick start page

reference/features/configuration.md
=> Update Configuration: CLI flags and environment variables

.code-samples.meilisearch.yaml, learn/core_concepts/relevancy.md, reference/api/ranking_rules.md
Removed wordsPosition, switched order of typo and words.
=> v0.21: ranking rules

create/how_to/postman_collection.md
Anglicize some French-sounding phrases, smooth out the English wording and make it consistent.
=> Improve wording in postman_collection.md

.vuepress/public/sample-template.yaml
Update code sample template to remove old one
=> Change search code in code sample template

reference/features/known_limitations.md
=> Fix wording

learn/getting_started/quick_start.md
According to this feedback:
https://github.com/meilisearch/MeiliSearch/issues/1369#issuecomment-863414323
@meilisearch/docs-team feel free to close if you think the current version is more relevant.
=> Update getting started

learn/getting_started/quick_start.md
wouhou 🎉 Be clicking on movies.json it should download it
fixes: #954
=> Make movie.json downloadable in one click

learn/getting_started/quick_start.md
Thanks to @curquiza and @bidoubiwa for the feedback!
=> Fix quick start recommended requirements

create/how_to/postman_collection.md
In the same idea as making movies.json downloadable :)
=> Make postman collection downloadable

reference/features/known_limitations.md
A few wording suggestions and cutting bits of text that don't add much in the way of actual information.
=> Feature reference audit: known limitations

learn/what_is_meilisearch/features.md, reference/api/search.md, reference/features/search_parameters.md, reference/under_the_hood/concat.md
Updates learn/what_is_meilisearch/features, reference/api/search, and reference/features/search_parameters so they all briefly mention phrase search and how to use it.
=> Add phrase search

reference/features/search_parameters.md
Following this confusion https://github.com/meilisearch/MeiliSearch/issues/1527
=> Add warning for matches

.vuepress/config.js, resources/faq.md, resources/open-api-readme.md
When on /, if I click on resources > faq with right-click and open new tab I have a 404.
This seems to fix this behavior. Let me know if I should open this PR against master or the v021 branch
=> Fix permalink on / for faq & open-api-readme

reference/api/stats.md
Rename fieldsDistribution to fieldDistribution.
=> v0.21: fieldDistribution

learn/what_is_meilisearch/telemetry.md
=> Remove wrong telemetry sentence

.code-samples.meilisearch.yaml, reference/features/authentication.md
=> Add curl header authentification example

learn/getting_started/quick_start.md
=> Make getting started html example consistent

.vuepress/public/postman/meilisearch-collection.json
- Add `sortableAttributes`
- Fix `GET /search` parameter default value
=> Add new Postman collection for v0.22.0

learn/getting_started/quick_start.md
Updated quick start guide to add numbered bullets
=> Updated quick start guide to add numbered bullets

reference/under_the_hood/indexation.md, resources/faq.md
v0.22 will feature a new, reworked indexer. This has implications for indexation performance and is a good opportunity for a more in-depth article on the subject.
- ~~reference/under_the_hood/storage: review page~~ This page is being updated directly by the core team on #1106
=> v0.22: Indexer

reference/under_the_hood/datatypes.md
Update soft/hard separators list. [Issue](https://github.com/meilisearch/documentation/issues/1029)
=> Update soft/hard separators list

learn/what_is_meilisearch/sdks.md
=> Add strapi plugin to SDKs and libraries list

reference/api/documents.md
Clarify primary key. Closing https://github.com/meilisearch/documentation/issues/934
=> Clarify primary key

learn/advanced/snapshots_vs_dumps.md, reference/features/dumps.md, yarn.lock
=> Add warning about importing dump versions

reference/features/filtering_and_faceted_search.md
Replace warning with a note on expected behavior and add warning on nested arrays and objects.
Closes #1126
=> Update filtering feature reference

index.md
Add a discreet message in the documentation about the cloud-hosted closed beta.
=> Add the link to join the cloud-hosted beta

.vuepress/public/sample-template.yaml, reference/api/README.md, reference/api/documents.md
=> add credentials to POST requests

reference/api/dump.md, reference/features/dumps.md
=> Add details to dumps api and feature references

reference/features/configuration.md
I have tried to cover all the configuration options. Please feel free to comment if any changes are required.
Closes #1039
=> Added `Expected value` fields to configuration options

learn/what_is_meilisearch/features.md, reference/api/search.md, reference/features/search_parameters.md
=> update placeholder search explanation

README.md
Friendship w/ hacktoberfest ended, now codevember is my best friend
=> Remove hacktoberfest from readme

.code-samples.meilisearch.yaml, .vuepress/public/sample-template.yaml, reference/features/filtering_and_faceted_search.md
=> Remove unused code samples

reference/api/displayed_attributes.md, reference/api/distinct_attribute.md, reference/api/filterable_attributes.md, reference/api/ranking_rules.md, reference/api/searchable_attributes.md, reference/api/settings.md, reference/api/sortable_attributes.md, reference/api/stop_words.md, reference/api/synonyms.md
=> consistent order of link&warning in API Refernces

reference/features/filtering_and_faceted_search.md
=> document `TO` filter

learn/what_is_meilisearch/telemetry.md, reference/features/configuration.md, resources/faq.md
Update documentation to reflect the upcoming changes to our telemetry stack and increase transparency.
=> v0.24 telemetry

errors.yaml, learn/advanced/asynchronous_updates.md, reference/api/README.md, reference/features/geosearch.md, resources/faq.md
=> v0.24-update errors

.code-samples.meilisearch.yaml, .vuepress/public/sample-template.yaml, learn/getting_started/quick_start.md
…ning of undefined behavior if they search before indexing finishes
closes #638
=> users should check the index status before they start searching

resources/faq.md
fix outdated reference to faceted fields
=> faceted -> filterable

learn/advanced/asynchronous_updates.md
=> v0.24: Update Asynchronous Updates guide code sample

learn/getting_started/quick_start.md
=> Make default search limit more prominent

reference/features/settings.md
Also avoid confusion with configuration, which is instance-level
=> Clarify that settings are index-level

learn/core_concepts/relevancy.md
=> Clarify attribute ranking order example

create/how_to/gcp.md
Updating the GCP URL on the deploy page
=> Update gcp version to v0-24-0

.code-samples.meilisearch.yaml, .vuepress/public/sample-template.yaml
=> add settings_guide_sortable_1 to code-samples and template

reference/features/configuration.md
Fixes a small styling issue in `configuration.md`
Thank you so much for contributing to MeiliSearch!
=> Fix small styling issue in configuration.md

reference/features/search_parameters.md
=> Fixed result object and documentation for Matches in Search parameters

errors.yaml
Just what the title says.
Thanks @bb for the [heads up](https://meilicommunity.slack.com/archives/CP9DVS1RQ/p1638351289362000?thread_ts=1638306462.354600&cid=CP9DVS1RQ).
=> Fix broken link in errors.yaml

.github/workflows/check-links.yml, .github/workflows/gh-pages-scraping.yml
Fixes [CI environment that updated to node 16](https://github.com/actions/virtual-environments/issues/4446) while the documentation is not yet compatible with node 16.
Thank you so much for contributing to MeiliSearch!
=> Specify node version in CI jobs

learn/advanced/datatypes.md
Just what it says in the title, plus a rewording here and there, nothing fancy
=> Change header values + add [[toc]] to datatypes

learn/advanced/updating.md
Thank you so much for contributing to MeiliSearch!
=> Update apt package name

learn/advanced/indexation.md, resources/faq.md
This is the exhaustive list of tips we currently know to speed the indexation and remove the crashes. I want to make a dedicated place in the docs so that anyone can link it in issues, slack discussions..etc
=> Add tips to speed up indexation and remove crashes

learn/advanced/snapshots_vs_dumps.md, learn/advanced/updating.md, reference/features/dumps.md
=> v0.25: Drop support for dump V1

reference/features/search_parameters.md
=> v0.25: Update to matches search parameter

reference/api/README.md
=> Fix authorization code sample renamed in v0.25

learn/cookbooks/gcp.md
Updating the GCP URL on the deploy page for `v0.25.0`.
Thank you so much for contributing to MeiliSearch!
=> Update gcp version to v0-25-0

learn/what_is_meilisearch/comparison_to_alternatives.md
Due to issues with how github handles PRs based on branches deleted by the original author, it is impossible to merge #1336 now.
This PR simply adds the previously accepted changed on #1336.
Credits go to @ferdi05 for the table and @maryamsulemani97 for proofreading and review.
=> Add competitor comparison table

reference/features/search_parameters.md
=> displayedAttributes take priority over attributesToRetrieve

.vuepress/components/linkButton.vue, .vuepress/styles/index.styl
Previous hover effect was ugly
=> Improve getting started hover effect

learn/getting_started/whats_next.md
=> Add back missing word

.vuepress/config.js
Add the new analytics link. The old one should stay here for a while otherwise we will lose history.
=> Add a second fathom link

.code-samples.meilisearch.yaml, reference/api/indexes.md
=> Make index code samples more consistent

reference/api/stats.md
=> Update Get stats of all indexes example

learn/what_is_meilisearch/comparison_to_alternatives.md
Update the ETA of the Firebase integration
=> Update the ETA of the Firebase integration

.code-samples.meilisearch.yaml
=> Add missing backslash to code samples

learn/getting_started/quick_start.md
following on #1471, I added a small warning for the user to avoid using meilisearch on docker on macOS and windows.
=> add warning about docker on macOS

.vuepress/public/sample-template.yaml
Remove duplicate code sample key from `sample-template.yaml`
=> Remove duplicate key

learn/advanced/dumps.md, reference/api/keys.md
=> replace /error with actual error

learn/getting_started/quick_start.md
Fix docker install instructions.
Closes #1484
=> Change Meilisearch to meilisearch in Docker command

.vuepress/config.js
=> Update documentation social image

reference/api/overview.md
Change external link to internal link.
=> Fix link to errors page

learn/what_is_meilisearch/telemetry.md
=> v0.26: Update telemetry table

learn/advanced/known_limitations.md
=> v0.26: Filter expressions limited to 2000 concatenated filters

learn/advanced/snapshots.md, learn/configuration/instance_options.md
=> v0.26: instance options new flag behavior

learn/configuration/instance_options.md
Based on @dichotommy's review of [PR#1444](https://github.com/meilisearch/documentation/pull/1444)
Made all the changes except adding the flag emoji, it fails the checks
=> v0.26-updated flag behavior

.vuepress/config.js, learn/getting_started/quick_start.md
=> Two negligible typo fixes

learn/advanced/updating.md
If I'm not wrong, according to this new addition in the [spec](https://github.com/meilisearch/specifications/pull/122/files) (sorry I should have done it before), the version number is not the right one in the note.
=> Fix note in updating.md guide

learn/getting_started/quick_start.md
Closes #1457 
Not sure if the note at line 380 is a good idea, but it looked weird without it
=> Add front-end integration step back to Quick Start

learn/security/master_api_keys.md
Updates the master key format to valid UTF-8 characters
=> update masterkey format

.code-samples.meilisearch.yaml, learn/core_concepts/indexes.md, reference/api/indexes.md
This PR updates all index responses to include the `name` field
=> update indexes API reference

package.json, yarn.lock
Confirmed by @bidoubiwa, we don't use moment anywhere
=> remove moment

.vuepress/config.js, learn/what_is_meilisearch/comparison_to_alternatives.md, learn/what_is_meilisearch/sdks.md
closes https://github.com/meilisearch/documentation/issues/1558
=> add the Firebase/firestore integration

learn/getting_started/quick_start.md
The React example had some problems which are fixed by this PR: 
- usage of functional components + arrow function components (inconsistency)
- extraneous space
=> Update react example for consistancy

.vuepress/config.js
Adds the missing DO integration to the `Integration` menu
Feel free to close my PR if it was removed on purpose
@alallema FYI :)
=> Add DO to integration menu

learn/advanced/updating.md
Add information about how to find data.ms in cloud providers, for the updating guide
Fixes #1571 
=> Add information about how to find data.ms in cloud providers, for the updating guide

reference/api/search.md
This PR is related to https://github.com/meilisearch/documentation/issues/748.
=> update type of hits in search response

package.json, yarn.lock
remove popperjs as we no longer use it
=> remove popperjs

.vuepress/public/postman/meilisearch-collection.json
- Add typo-tolerance settings
- Add `cropMarker`, `higlightPreTag`, `highlightPostTag`
=> Update postman collection for v0.27.0

learn/advanced/updating.md, learn/getting_started/quick_start.md
=> v0.27: Update Docker paths

learn/what_is_meilisearch/telemetry.md
=> v0.27: add new telemetry datapoints

learn/what_is_meilisearch/language.md
=> v0.27: Add Japanese tokenizer

reference/api/indexes.md
=> primary key can be changed if index is empty

learn/advanced/known_limitations.md, reference/api/search.md
=> v0.27: Queries limited to 1000 returned results

learn/advanced/indexation.md, learn/configuration/instance_options.md
This PR updates `/learn/configuration/instance_options.md` and `/learn/advanced/indexation.md` with two new instance options: `--max-indexing-memory` and `--max-indexing-threads`.
Resolves #1581
None.
=> v0.27: New instance options

.code-samples.meilisearch.yaml, reference/api/search.md
Resolves #1579, #1578
- `search_parameter_guide_crop_1`
- `search_parameter_guide_crop_marker_1`
- `search_parameter_guide_highlight_tag_1`
=> v0.27: update search parameters related to cropping and highlighting

learn/advanced/datatypes.md, learn/advanced/filtering_and_faceted_search.md, learn/advanced/sorting.md
- update `/learn/advanced/datatypes.md`
- Make `Objects` an H2  
- remove outdated content from `/learn/advanced/filtering_and_faceted_search.md` and `/learn/advanced/sorting.md`
=> updatd nested objects

README.markdown
Add warning for contributors that PRs which haven't been updated by the author in 7+ days will be closed.
=> Add timeframe warning to readme

learn/advanced/asynchronous_operations.md, learn/advanced/filtering_and_faceted_search.md, learn/advanced/geosearch.md, learn/advanced/sorting.md, learn/configuration/typo_tolerance.md, learn/core_concepts/indexes.md, learn/getting_started/quick_start.md, reference/api/displayed_attributes.md, reference/api/documents.md
Remove any extra spaces+repeated words. Related to https://github.com/meilisearch/documentation/pull/1646
=> Vale: remove extra space+repeated words

learn/getting_started/quick_start.md
Adds document formats to "Add documents" step of the quick start
=> add document format to quickstart

.code-samples.meilisearch.yaml
=> update code sample to add missing -

learn/getting_started/getting_ready_for_production.md, learn/getting_started/quick_start.md
Add some basic info on authorization to the quick start
- Do we have too many links in this section?
- Should we mention how API keys are different from the master key? Or would that be too much information?
=> add authorization to quick start

.vuepress/config-path-checker/README.md, learn/configuration/typo_tolerance.md
minor updates for https://github.com/meilisearch/documentation/pull/1646
=> minor updates for vale

learn/cookbooks/aws.md, learn/what_is_meilisearch/features.md, learn/what_is_meilisearch/overview.md
=> Update MeiliSearch to Meilisearch

learn/getting_started/customizing_relevancy.md
Update `displayed attribute` to `distinct attribute`
=> Fix typo in  `customizing_relevancy.md`

reference/api/error_codes.md
It will be easier for the users to be redirected to the right place
=> Add link about opening an issue

.vuepress/public/postman/meilisearch-collection.json
=> Update postman collection for v0.28.0

reference/api/search.md
=> v0.28: Smart cropping

.vuepress/components/linkButton.vue
=> Shrink clickable area of the Quick Start button

reference/api/tasks.md
I've suggested some data to make this PR, but feel free to change it.
Btw, I missed some information about the response. Since the task routes have a different way of pagination, it may be good to explain a little about it (sorry if this is solved somewhere else).
https://docs.meilisearch.com/reference/api/tasks.html#get-tasks
=> The tasks response has missing information

learn/getting_started/quick_start.md
=> Adding Railway to the Cloud Deploy options

reference/api/overview.md, resources/faq.md
part of #1593 
This PR moves the error types FAQ to API reference/overview
=> FAQ: remove errors

learn/getting_started/algolia_migration.md
=> update algolia guide

.code-samples.meilisearch.yaml
Makesthe documentation every so slightly easier to read by fixing the indentation for one of the code samples.
=> Update .code-samples.meilisearch.yaml to make it easier to read

learn/getting_started/quick_start.md
=> update quick start code sample

.code-samples.meilisearch.yaml
=> Method is PATCH for /indexes/.*/settings

learn/core_concepts/documents.md, resources/faq.md
part of #1593 
Moves content from the `400 - Bad Request` FAQ to Core concepts/Documents
=> remove 400 - Bad Request FAQ

.vale/styles/Vocab/word_list/accept.txt, .vale/styles/style_guide/Indexing.yml, learn/advanced/pagination.md, learn/advanced/tokenization.md, learn/getting_started/algolia_migration.md, learn/what_is_meilisearch/telemetry.md, resources/faq.md
This PR fixes typos and adds words to `accept.txt`
=> minor vale related changes

reference/api/version.md
part od #1351 
Updates `version.md`
=> API reference: update version.md

learn/getting_started/getting_ready_for_production.md
Part of #1717 
This PR adds multitenancy and tenant tokens to the 101
=> Update Meilisearch 101: add tenant tokens

.code-samples.meilisearch.yaml, .vuepress/public/sample-template.yaml, learn/getting_started/customizing_relevancy.md
=> update 101: add faceting and pagination

reference/api/stats.md
=> API reference: update stats.md

.vuepress/code-samples/components/codeSamples.vue
=> Change code sample div class name

reference/api/search.md
Part of #1351 
This page's sidebar will look different from the rest because of `sidebarDepth: 2`
=> API reference: update search.md

learn/advanced/updating.md
=> Add Slack link to `updating.md`

reference/api/error_codes.md
closes #1747
I removed the "Error list" heading as it felt redundant and made each error an H2
=> add errors to sidebar

learn/cookbooks/digitalocean_droplet.md
This PR updates `learn/cookbooks/digitalocean_droplet.md`
part of https://github.com/meilisearch/documentation/issues/1719
=> update digital ocean

learn/getting_started/quick_start.md, learn/what_is_meilisearch/search_preview.md
=> disable search preview

learn/configuration/settings.md
=> standardize formatting

learn/core_concepts/primary_key.md
=> primary key: update responses

learn/getting_started/quick_start.md
=> v0.29: update Docker tag

learn/advanced/storage.md
=> v0.29: Soft deletion

learn/configuration/instance_options.md
None
Related to PR [#2839](https://github.com/meilisearch/meilisearch/pull/2839) in the main repo, I saw that the documentation seemed to contain typos in the log-levels descriptions.
This fixes them.
=> docs: uniform log-level style

.vuepress/docs-scraper/docs-scraper.config.json
=> show text in backticks in search results

reference/api/search.md
=> Fix typo on `/reference/api/search.md`

learn/advanced/known_limitations.md
=> Known limitations: add maximum number of concurrent requests

learn/configuration/displayed_searchable_attributes.md, learn/configuration/instance_options.md, learn/core_concepts/indexes.md, learn/getting_started/algolia_migration.md, reference/api/error_codes.md, reference/api/settings.md
fixes some of the issues mentioned in #1711
=> remove semicolons and `indexation`

learn/advanced/updating.md
=> stop meilisearch during upgrade

reference/api/settings.md
=> Stop word lists for different languages

learn/core_concepts/relevancy.md
=> clarification on functioning of ranking rules

learn/getting_started/quick_start.md
=> Incorrect information regarding instant-meilisearch

reference/api/settings.md
The settings page says updating all settings will cause re-indexing. This is not true. 
Only updating these 5 settings triggers re-indexing: 
https://github.com/meilisearch/specifications/blob/main/text/0123-settings-api.md#41-triggering-documents-re-indexing
Also closes #824
=> update settings page

reference/api/error_codes.md
=> Errors page: list errors in alphabetical order

.vuepress/styles/index.styl
=> update link color for tips

learn/cookbooks/gcp.md
This PR updates the address of the new GCP image for v0.29.1
=> Update GCP image address for v0.29.1

.vuepress/components/RouteHighlighter.vue, reference/api/settings.md, reference/api/version.md
closes #1857 + #1948
~~If anyone has any other color suggestions, we can change this~~
Updated to [Swagger's](https://github.com/swagger-api/swagger-ui/blob/6ae2693d47397a919370eb19149f5514cb2f99f2/src/style/_variables.scss#L51) colors
=> update api references

learn/getting_started/quick_start.md
=> add customization options to quick start

.vuepress/config.js
=> fix "Edit this page" link

.code-samples.meilisearch.yaml, .github/workflows/checks.yml, .github/workflows/deploy.yml, .vuepress/code-samples/sdks.json, .vuepress/public/sample-template.yaml, README.markdown, learn/contributing/contributing_to_docs.md, learn/contributing/overview.md, learn/cookbooks/search_bar_for_docs.md
Fixes #1270 
- Change branch name from master to main
=> Change branch name from master to main

learn/advanced/dumps.md, learn/advanced/snapshots.md, learn/advanced/snapshots_vs_dumps.md, learn/advanced/storage.md
=> Add more mentions of database location

.github/workflows/checks.yml, learn/cookbooks/docker.md, learn/getting_started/quick_start.md
=> v.30: Update Docker and Source tags

.code-samples.meilisearch.yaml, .github/workflows/checks.yml, .vale/styles/Vocab/word_list/accept.txt, .vuepress/public/sample-template.yaml, reference/api/overview.md
=> v.30: Support gzip, brotli, and deflate

.github/workflows/checks.yml, learn/getting_started/quick_start.md, learn/security/master_api_keys.md, reference/api/keys.md, reference/errors/error_codes.md
=> v0.30: new error  missing master key

.code-samples.meilisearch.yaml, .github/workflows/checks.yml, .vuepress/public/sample-template.yaml, learn/advanced/pagination.md, reference/api/search.md, reference/api/settings.md
=> v0.30: Exhaustive pagination updates

.github/workflows/checks.yml, learn/advanced/filtering_and_faceted_search.md
=> v0.30: filtering and NaN/infinity values

.vuepress/public/postman/meilisearch-collection.json
Added:
- pagination
- task cancel
- task deletion
- index swap
updated
- some filter naming
=> Update Postman collection for v0.30.0

.github/workflows/checks.yml, .vuepress/config.js
You can use 's' as well as '/' to focus on the searchbar.
I figured it may be a good idea to change this, since at least one person was confused by the previous placeholder text.
=> Change search placeholder text

.github/workflows/checks.yml, learn/what_is_meilisearch/telemetry.md
=> v0.30: Update telemetry table

.code-samples.meilisearch.yaml, learn/getting_started/quick_start.md
Fixes https://github.com/meilisearch/documentation/issues/2005
- Mentioning primary key in the add documents section
=> Mentioning primary key in the add documents section

learn/configuration/instance_options.md, learn/getting_started/quick_start.md
Updates quick start+ instance options
=> v0.30: update quick start+instance options

learn/advanced/storage.md
Update Wayback machine LMDB blogpost link 
Thanks @Kerollmops
=> update LMDB blogpost link

.code-samples.meilisearch.yaml
Fixes #2022 
Thanks @Kerollmops for spotting it! 🙌🏻
=> Fix index swap code sample json payload

reference/api/search.md
- This PR fixes this example response: https://docs.meilisearch.com/reference/api/search.html#example-3. The returned document shown in the example response does not contain `shifu` in any of its attributes.
=> Fix search example response

learn/getting_started/quick_start.md
=> update quick start customization options

learn/cookbooks/gcp.md
This PR updates the address of the new GCP image for v0.30.4
=> Update GCP image address for v0.30.4

learn/advanced/storage.md
=> LMDB storage: clarify disk space usage limits, minor wording changes

learn/advanced/asynchronous_operations.md
Add other async operations to the async guide
=> update async guide to add async opertaions

learn/getting_started/quick_start.md
- Fix apt install instructions.
In `sudo echo bla > /filename`, the `sudo` doesn't apply to the stuff after the pipe. This fixes it by using `sudo tee` to write the text to the file.
=> Fix apt install instructions

learn/core_concepts/indexes.md
=> comparison of implicit vs. explicit index creation

.code-samples.meilisearch.yaml, .vuepress/public/sample-template.yaml, learn/advanced/asynchronous_operations.md, reference/api/tasks.md
=> Asynchronous operations guide review

learn/configuration/instance_options.md
Add `OFF` log level
closes #2074
=> add `OFF` log level

.vuepress/public/postman/meilisearch-collection.json
=> Postman: update cancel task path

learn/what_is_meilisearch/comparison_to_alternatives.md
=> Update a few items in the table

learn/cookbooks/running_production.md
Fixes #3243
- added system user for meilisearch
- set basic config using config file
- save files to proper directories
=> Updated systemd service

learn/cookbooks/running_production.md
=> Fix config.toml download link to point to the last version (v0.30.5) #2115

.vuepress/config.js
=> Change Firebase location in integrations dropdown

README.markdown
- Makes it clearer how to contribute and link images and other assets
- [X ] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [ X] Have you read the contributing guidelines?
- [ X] Have you made sure that the title is accurate and descriptive of the changes?
=> Add section for how to add images

learn/cookbooks/docker.md, learn/getting_started/quick_start.md
=> v1.0: Update docker

.vuepress/public/postman/meilisearch-collection.json
=> v1.0: Update Postman collection

reference/errors/overview.md
=> v1.0: New error type :`system`

reference/api/search.md
_Note for reviewers:_ the only section that needs to be reviewed is on lines 298-302, despite the size of the diff.
Closes #2092
=> v1.0: Clarify non-spacing mark normalization

learn/advanced/dumps.md, learn/advanced/updating.md, learn/configuration/instance_options.md, learn/what_is_meilisearch/telemetry.md, reference/api/dump.md
=> v1.0: Rename dumps instance option

learn/cookbooks/running_production.md
=> v1.0: Config file link

learn/advanced/sorting.md, learn/what_is_meilisearch/features.md
Remove unnecessary content, shorten existing text, add new three new major features.
Fixes #2117
=> Update Features page

learn/getting_started/quick_start.md
- Converted second intro paragraph to bullet points
=> second paragraph converted to bullets

learn/getting_started/installation.md
Following: https://github.com/meilisearch/meilisearch/discussions/3459#discussioncomment-4903166
=> Fix `apt` command for v1.0

learn/configuration/instance_options.md, learn/cookbooks/running_production.md
Latest = the latest stable git tag (so v0.30.5 currently)
main = the branch containing the most recent commit (so more commits than in v0.30.5 currently)
=> Use latest instead of main when requesting the default config file

learn/core_concepts/documents.md
@guimachiavelli edit: stopgap solution, does not fix any issues
=> fix faq link 404

learn/advanced/dumps.md
- Catch up by removing outdated info about the dump process. It's now possible to jump to the last version (currently `v1.0`) from any version starting from `v0.15`)
=> Remove outdated info about the dump process

.vuepress/public/sample-template.yaml
Fixes #2167 
- removes unused code from `.vuepress/public/sample-template.yaml `
```diff
from line 121 to 123:
- tenant_token_guide_fragment_rules_1: |-
- tenant_token_guide_fragment_key_1: |-
- tenant_token_guide_fragment_expiry_1: |-
```
=> Remove unused code from sample-template.yaml

.vale/styles/Vocab/word_list/accept.txt, learn/contributing/contributing_to_docs.md, learn/contributing/overview.md
=> Review contributing guides

learn/advanced/pagination.md, reference/api/search.md, reference/api/settings.md
=> Warnings against raising `maxTotalHits` limit

LICENSE
=> Update license to 2023

sidebarLearn.json
update `sidebarLearn.js` to remove nesting
=> update `sidebarLearn.js` to remove nesting

learn/core_concepts/documents.md
=> v1.1: Batch document additions and deletions

.vuepress/public/postman/meilisearch-collection.json
=> v1.1: Update postman

.vuepress/config.js, learn/experimental/metrics.md
=> v1.1: Metrics

learn/advanced/known_limitations.md, learn/what_is_meilisearch/comparison_to_alternatives.md
=> v1.1: Update index size/count limits

learn/what_is_meilisearch/telemetry.md
=> v1.1: Telemetry

learn/core_concepts/documents.md
update `documents.md` to add link to displayed and searchable attributes guide
=> update `documents.md` to add link to displayed&searchable attributes guide

home.mdx
With these changes the Home Featured component would look like this:
- Shows how the Featured component items could be better styled and customized.
(For this changes to come live I need to manually deploy some changes, so it won't be immediately reflected after merging)
=> [Suggestion]: fixes on Featured component

learn/getting_started/installation.mdx
Part of #2245 
Migrates changes from #2250
=> New site: migrate changes from PR 2250

learn/core_concepts/documents.mdx
Part of #2245 
This PR migrates changes from #2254
=> New site: migrate changes from PR 2254

learn/getting_started/quick_start.mdx
Part of #2245
This PR migrates changes from #2233
=> New site: migrate changes from PR 2233

learn/advanced/indexing.mdx
Part of #2245 
This PR migrates the changes from #2230
=> New site: migrate changes from PR 2230

config/sidebar-reference.json, learn/what_is_meilisearch/comparison_to_alternatives.mdx, learn/what_is_meilisearch/features.mdx, reference/api/multi_search.mdx
Update `multi-index` to `multi-search`
=> update multi-index to multi-search

home.mdx
Trying to improve the home slightly
=> Migration: Trying to improve the home slightly

learn/advanced/faceted_search.mdx
Updates images and gif links in the faceted guide to absolute links to the GitHub raw file
=> Update asset links in faceted guide

search.sh
This is just a simple search shell function that ChatGPT created for me, intended for local use, does not need to be stored in git remote
=> Remove search sh

home.mdx
We are trying to display an H2 in one of the <Featured> components on the homepage.
=> Change content string to JSX interpolation

learn/contributing/overview.mdx, learn/getting_started/installation.mdx, learn/index_settings/displayed_searchable_attributes.mdx, learn/what_is_meilisearch/sdks.mdx
=> Migration: fix broken links

home.mdx
- Yet again, fixes JSX syntax erros. CSS should be an object.
=> [FIX]: Style syntax on JSX

home.mdx
Fixes layout shift on homepage reload.
- Uses new custom component `Heading` with the prop `noAnchor` that avoids the creation of a link wrapper, since it's not necessary on the homepage. The rest of headings go untouched and are wrapped in anchor tags for hash navigation.
=> [FIX]: Use Heading custom component

learn/advanced/faceted_search.mdx, learn/advanced/filtering.mdx, learn/advanced/geosearch.mdx, learn/advanced/sorting.mdx, learn/configuration/instance_options.mdx, learn/contributing/contributing_docs.mdx, learn/core_concepts/documents.mdx, learn/core_concepts/indexes.mdx, learn/core_concepts/primary_key.mdx, learn/core_concepts/relevancy.mdx, learn/deployment/aws.mdx, learn/deployment/digitalocean.mdx, learn/deployment/gcp.mdx, learn/deployment/qovery.mdx, learn/getting_started/installation.mdx, learn/index_settings/typo_tolerance.mdx, learn/security/master_api_keys.mdx, learn/security/tenant_tokens.mdx, learn/update_and_migration/algolia_migration.mdx, learn/update_and_migration/previous_docs_version.mdx, learn/update_and_migration/updating.mdx, reference/api/search.mdx, reference/api/settings.mdx
This PR fixed the "On this page sidebar" of some pages to include H3s and H4s so users can easily jump between sections
=> Migration: fix sidebar depth

.code-samples.meilisearch.yaml
Add `filtering_update_settings_1` to `.code-samples.meilisearch.yaml`
=> Migration: Add missing code sample

learn/core_concepts/documents.mdx
Updates faq link to relative link
=> Migration: Update faq link to relative link

learn/advanced/asynchronous_operations.mdx, learn/what_is_meilisearch/comparison_to_alternatives.mdx, learn/what_is_meilisearch/features.mdx
Updates sidebar depth for async operations and comparison to alternatives
=> Migration: update sidebardepth for longer pages

learn/advanced/geosearch.md
Fixes https://github.com/meilisearch/documentation/issues/2340
- This PR removes unnecessary spaces in the CSV file example to avoid issues like this: https://github.com/meilisearch/documentation/issues/2340 in the future.
=> Fix CSV file example in Geosearch guide

learn/contributing/contributing_docs.mdx
=> Migration: Update local install guidelines

.github/workflows/scraper.yml, docs-scraper.config.json
- Now the scraper points to meilisearch.com/docs.
- Github job await for success or failure instead of retrying every time.
=> Update scraper url and action behavior

learn/getting_started/quick_start.mdx, learn/inner_workings/storage.mdx, learn/meilisearch_101/customizing_relevancy.mdx
This PR updates the download link for the movies dataset
=> Migration: Update download links

learn/inner_workings/storage.mdx
=> [FIX]: extra closing tag

.github/workflows/scraper.yml, docs-scraper.config.json
=> [FIX]: docs scraper action

learn/cookbooks/running_production.mdx
=> add execute permission to `running_production.mdx`

learn/update_and_migration/updating.mdx
=> updating guide: rename`--dumps-dir` to `--dump-dir`

learn/deployment/aws.mdx, learn/deployment/gcp.mdx, learn/what_is_meilisearch/sdks.mdx
closes #2417 
This PR updates all links except in the Integrations dropdown
=> update cloud provider links

learn/core_concepts/documents.mdx
closes #878 
I didn't update the storage page as it was mostly on LMDB
=> Clarify storage across indexes

learn/inner_workings/storage.mdx
This PR fixes typos and grammar in `storage.md`
=> fix typos in `storage.md`

learn/getting_started/installation.mdx
closes #2015 
- Do we need to add any warnings or notes for specific versions?
- Is there anything we can add about commonly encountered errors with installing old versions?
=> Add documentation on installing older Meilisearch versions

.code-samples.meilisearch.yaml, reference/api/multi_search.mdx, reference/api/settings.mdx, sample-template.yaml
Fixes #2424 
-Removes the unused code sample of faceted_search_2  from these two docs .code-samples.meilisearch.yaml and sample-template.yaml
Please check if your PR fulfils the following requirements:
=> Unused code samples are removed

learn/core_concepts/documents.mdx
=> v1.2: Add accepted CSV datatypes

learn/core_concepts/documents.mdx
=> v1.2: Update auto-batching note

learn/cookbooks/docker.mdx, learn/getting_started/installation.mdx
=> v1.2: Update Docker image tags

learn/advanced/filtering.mdx, reference/api/search.mdx
Adds description of new `IS EMPTY`, `IS NULL` operators.
Closes #2415
=> v1.2: New filter operators

learn/what_is_meilisearch/telemetry.mdx
Add new datapoints to telemetry table and fix minor table white space issues.
Closes #2414
=> v1.2: Update telemetry table

learn/contributing/contributing_docs.mdx, learn/cookbooks/postman_collection.mdx, learn/cookbooks/search_bar_for_docs.mdx, learn/core_concepts/primary_key.mdx, learn/deployment/aws.mdx, learn/what_is_meilisearch/overview.mdx
This PR updates some links in the documentation which are currently broken.
=> Update broken links

learn/what_is_meilisearch/comparison_to_alternatives.mdx
Fixes #2191 
- Elasticsearch's source code licensing returns the "page not found" problem mentioned in this issue is already solved.
- Moved elasticsearch from open-source to closed-source section and in the conclusion changed elasticserch's details as a closed-source search engine.
=> Comparison to alternatives Updated

learn/what_is_meilisearch/overview.mdx
closes #2391 
I removed the image under "[Give it a try!](https://www.meilisearch.com/docs/learn/what_is_meilisearch/overview#give-it-a-try)" as it wasn't adding anything(it's an image of the search preview without any indexes). We have a Demo section on this page, so I don't think we need another gif/image here.
Redirects added in https://github.com/meilisearch/meilisearch.com/pull/129
=> Improve site organization + visibility: Update /learn/what_is_meilisearch/overview.mdx

running-locally.md
Reviewers: please run the steps on your machines as part of your review.
There might be a few points during the process where you'll see a few warnings and errors, both on terminal and while browsing the local copy of the website. This is expected and shouldn't really influence our testing. Let me know if that's not the case and any errors actually prevent you from working.
=> Add internal guide on how to run docs site locally

learn/fine_tuning_results/filtering.mdx
closes #2463 
Updates the syntax for the `TO` operator in `filtering.mdx`
=> Update `TO` operator syntax

README.md
Fixes #2483 
- fixes broken link to to contribution overview in ReadME.md file
=> Fixed a broken link to contribution overview

learn/index_settings/typo_tolerance.mdx
In response to [this Slack comment](https://meilisearch.slack.com/archives/C054QUSPC5S/p1687934624451809?thread_ts=1687884023.911019&cid=C054QUSPC5S) (internal company Slack)
Does this resolve the uncertainty @chayaline ?
=> Clarify minWordSizeForTypos limits

learn/meilisearch_101/filtering_and_sorting.mdx
Thanks to a tip from @CaroFG 🙏🏻
=> Fix broken link in filtering_and_sorting.mdx

learn/getting_started/installation.mdx
I follow the sentence we use in the Meilisearch README ([PR](https://github.com/meilisearch/meilisearch/pull/3895) in progress). Validated by @gmourier on this.
=> Adapt Cloud information to the new pricing

learn/what_is_meilisearch/telemetry.mdx
=> v1.3 telemetry updates

learn/cookbooks/docker.mdx, learn/getting_started/installation.mdx
=> v1.3: Update Docker image versions

.code-samples.meilisearch.yaml, learn/index_settings/displayed_searchable_attributes.mdx, reference/api/multi_search.mdx, reference/api/search.mdx, reference/errors/error_codes.mdx, sample-template.yaml
=> v1.3: `attributesToSearchOn`

reference/api/settings.mdx
Fixes broken links related to sorting in settings API reference. Thanks @CaroFG for spotting 🦅 👀
=> Fix broken links in settings.mdx

learn/experimental/overview.mdx
=> Experimental features: fix broken links in overview

reference/api/experimental_features.mdx
=> Experimental features API: fix response object table

home.mdx, learn/async/asynchronous_operations.mdx, learn/core_concepts/documents.mdx, learn/core_concepts/indexes.mdx, learn/core_concepts/relevancy.mdx, learn/fine_tuning_results/filtering.mdx, learn/fine_tuning_results/geosearch.mdx, learn/fine_tuning_results/sorting.mdx, learn/getting_started/search_preview.mdx, learn/index_settings/typo_tolerance.mdx, learn/security/tenant_tokens.mdx, learn/what_is_meilisearch/overview.mdx, reference/api/documents.mdx, reference/api/keys.mdx, reference/api/search.mdx, reference/api/settings.mdx, reference/errors/error_codes.mdx
=> Fix broken links reported on #2507

assets/misc/meilisearch-collection-postman.json
=> v1.4: Update Postman collection

resources/faq.mdx
This is a test of an SEO improvement. I want to use the title and description meta tags by adding them at the top of the documentation.
@guimachiavelli, if you merge this PR and check the title change on the /faq page, it would mean that editing all MDX files to add a title and description would significantly improve the SEO of the documentation.
=> Test SEO on FAQ.mdx

learn/inner_workings/datatypes.mdx, learn/what_is_meilisearch/comparison_to_alternatives.mdx
=> Clarify nested fields

learn/cookbooks/running_production.mdx
n/a
- fixes misleading documentation: https://www.meilisearch.com/docs/learn/cookbooks/running_production#41-create-a-service-file
=> improve service file documentation

.gitignore, .vscode/settings.json
We should not merge this kind of file. This kind of settings should be individually managed depending on the text editor of the contributor.
Let me know if I'm wrong and I miss something @guimachiavelli
=> Remove vscode file

learn/inner_workings/known_limitations.mdx
Fixes #2599
Removes the section "Maximum number of concurrent requests"  and it's subsections as mentioned in the issue
=> docs: removed max concurrent request limitation information

README.md, learn/getting_started/installation.mdx, learn/update_and_migration/migrating_cloud.mdx, learn/update_and_migration/updating.mdx, resources/faq.mdx
=> Update Discord links

learn/cookbooks/docker.mdx, learn/getting_started/installation.mdx
=> v1.5: Docker version bump

learn/inner_workings/tokenization.mdx
No Related issue
- Updates to provide more accurate information
=> Update tokenization.mdx for Korean pipeline

config/sidebar-learn.json, learn/experimental/overview.mdx, learn/experimental/puffin_reports.mdx, reference/api/experimental_features.mdx
=> v1.5: Puffin reports

learn/index_settings/synonyms.mdx
=> Clarify synonyms behaviour

learn/cloud/analytics.mdx
Fixes broken image links on Meilisearch Cloud analytics guide.
=> Fix analytics guide asset links

learn/configuration/instance_options.mdx
=> Add configuration instructions for cloud-hosted instances

learn/cloud/analytics.mdx
=> Add warning regarding Meilisearch Cloud analytics and `/multi-search`

learn/experimental/vector_search.mdx
wrong param to activate vector store for v1.5
- ...
=> replaced vectorSearch to vectorStore

config/sidebar-learn.json, learn/getting_started/installation.mdx, learn/getting_started/supported_os.mdx
Closes #2515
@Strift, you recently mentioned we might improve the SEO for some pages by splitting them in more focussed documents. Since I need a review anyway, I thought you might appreciate this.
=> Shorten installation guide

learn/core_concepts/documents.mdx
=> Clarify which operations are auto-batched

learn/cloud/analytics.mdx
Following this feedback: https://github.com/meilisearch/meilisearch/issues/4302#issuecomment-1880667253
=> Use https for cloud instead of http

learn/experimental/vector_search.mdx
=> v1.6: Vector search v2

learn/async/asynchronous_operations.mdx, learn/configuration/instance_options.mdx
=> v1.6: Task webhook URL

learn/cookbooks/docker.mdx, learn/getting_started/installation.mdx
=> v1.6: Update Docker images

assets/misc/meilisearch-collection-postman.json
=> v1.6: Update Postman collection

learn/what_is_meilisearch/telemetry.mdx
Update telemetry table with data points for:
=> v1.6: Update telemetry table

learn/experimental/vector_search.mdx
Following: https://github.com/orgs/meilisearch/discussions/677#discussioncomment-8147163
=> Fix example in vector search

learn/cloud/analytics.mdx
For some reason #2680 did not reflect my suggestions, despite the user seeming to have accepted them. This PR fixes that by pushing the final text.
=> Fix faulty #2680 merge

learn/experimental/vector_search.mdx
=> Explicitly state Meilisearch only supports BERT huggingface models

learn/front_end/react_instantsearch.mdx
=> Fix image URL

learn/cloud/analytics.mdx, learn/cloud/monitoring.mdx
=> Hotfix: asset path in Monitoring and Analytics guides

learn/async/task_webhook.mdx
Fixes issue with [OG image generation](https://meilisearch.slack.com/archives/C04GJ0KHRR6/p1707408056447189)
- Add metadata to task webhook guide
=> Add metadata to task webhook guide

learn/fine_tuning_results/filtering.mdx
Fixes a syntax typo in the filtering arrays combined with expressions
=> Fix filtering arrays typo

.github/workflows/scraper.yml, docs-scraper.config.json
- Adds embedders to meilisearch settings in scraper config
- Updates scraper workflow
=> Add embedders config to scraper

learn/cookbooks/docker.mdx, learn/getting_started/installation.mdx
=> v1.7: Docker version bump

learn/experimental/vector_search.mdx
=> v1.7: Updates to OpenAI embedder

config/sidebar-learn.json, learn/cookbooks/computing_hugging_face_embeddings_gpu.mdx, learn/experimental/vector_search.mdx
Closes #2736 
@Strift and @CaroFG, notifying you this PR includes a short guide aimed at enabling GPU usage with the Hugging Face embedding. It's aimed at advanced self-hosted users, but thought you might want to be aware of it.
=> v1.7: Add Hugging Face vector search updates

config/sidebar-learn.json, learn/experimental/overview.mdx, learn/experimental/replication_parameters.mdx
=> v1.7: Replication parameters

assets/misc/meilisearch-collection-postman.json
=> v1.7: Update Postman collection

docs-scraper.config.json
Add LLM synonyms in docs scraper config
=> Add LLM synonyms

learn/experimental/vector_search.mdx
- add hugging face organization user name to the hugging face model name 
HTTP 401 when configuring embedder
```ruby
{"message"=>"internal: Error while generating embeddings: error: fetching file from HG_HUB failed: request error: https://huggingface.co/bge-base-en-v1.5/resolve/main/config.json: status code 401.",
"code"=>"internal",
"type"=>"internal",
"link"=>"https://docs.meilisearch.com/errors#internal"},
```
downloading embedder actually works
=> Add huggingface organization to model name

learn/getting_started/cloud_quick_start.mdx
Adds Cloud getting started video
=> Add Cloud getting started video

config/sidebar-learn.json, learn/cookbooks/langchain.mdx, learn/experimental/vector_search.mdx
Fixes #2707 
- Adds Meilisearch >= v1.6 LangChain similarity search guide 
=> Add langchain tutorial

learn/data_backup/dumps.mdx
=> fixed Importing a dump header for self-hosted instance in dumps.mdx

.github/actions/validate-docs-links/src/checker.ts
- Fixes link-checker for json files
=> Refactor link-checker to work with json

learn/front_end/react_instantsearch.mdx
- Update the searchClient declaration according to the changes described in the [instant-meilisearch changelog](https://github.com/meilisearch/meilisearch-js-plugins/releases/tag/%40meilisearch%2Finstant-meilisearch%400.14.0)
=> Update search client declaration

learn/cookbooks/docker.mdx, learn/getting_started/installation.mdx
=> v1.8: Docker version bump

learn/what_is_meilisearch/telemetry.mdx
=> v1.8: Telemetry

.code-samples.meilisearch.yaml, reference/api/settings.mdx, reference/errors/error_codes.mdx
=> v1.8: Search cutoff

config/sidebar-learn.json, learn/experimental/overview.mdx, learn/experimental/search_queue_size.mdx, learn/inner_workings/known_limitations.mdx, reference/errors/error_codes.mdx
=> v1.8: Search request queue size

learn/experimental/vector_search.mdx
=> v1.8: Add new embedder sources

learn/experimental/vector_search.mdx
Documents the new embedder setting, `distributionShift`.
=> v1.8: Distribution shift

learn/cookbooks/postman_collection.mdx
=> Hotfix: Postman collection link

learn/what_is_meilisearch/language.mdx
Adds Swedish to list of languages with optimized support
=> Add Swedish to list of languages with optimized support

learn/core_concepts/documents.mdx
- Replaces the deprecated link ndjson.org
=> Replace deprecated link for ndjson

config/sidebar-learn.json
=> Hotfix: Fix full-text vs AI-powered search article title

config/redirects.json
Add `permanent: true` to all redirects.
Fixes #2878
=> Fix redirects

reference/api/search.mdx
Fixes #2881
- According to #2881 the style guide dictates to spell out numbers less than 10
- change plural 'performances' to 'performance'
- [ x ] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [ x ] Have you read the contributing guidelines?
- [ x ] Have you made sure that the title is accurate and descriptive of the changes?
=> Update search.mdx to style guide

learn/async/filtering_tasks.mdx
- as the original status is implemented as `canceled`, this caused confusion. This PR intended to fix the typo
=> correct typo from cancelled to canceled

.code-samples.meilisearch.yaml, reference/api/search.mdx
=> v1.9: Add `frequency` matching strategy

learn/core_concepts/relevancy.mdx
=> v1.9: Update ranking order when using the default value for `searchableAttributes`

assets/misc/meilisearch-collection-postman.json
=> v1.9: Postman

guides/indexing_best_practices.mdx, learn/configuration/configuring_index_settings.mdx, learn/core_concepts/documents.mdx, learn/security/multitenancy_tenant_tokens.mdx, learn/what_is_meilisearch/telemetry.mdx, migration-guide.md, reference/api/tasks.mdx
- Fix spelling errors found via `codespell -S assets -L sade,trough,tha`
=> Fix spelling errors

learn/getting_started/search_preview.mdx
=> fix: update search_preview.mdx

learn/analytics/events_endpoint.mdx
=> Fix link to analytics event binding guide

guides/front_end/react_quick_start.mdx, guides/front_end/vue_quick_start.mdx
- Updates the index name in react and vue quickstarts from `steam-video-games` to `steam-videogames`
=> Update index name on quickstarts

learn/experimental/vector_search.mdx, reference/api/settings.mdx
=> v1.10: AI search updates

.code-samples.meilisearch.yaml, reference/api/multi_search.mdx, reference/errors/error_codes.mdx
=> v1.10: Federated search

learn/filtering_and_sorting/filter_expression_reference.mdx
=> v1.10: `CONTAINS` filter operator

reference/api/documents.mdx
=> v1.10: Experimental feature: Edit documents endpoint

guides/docker.mdx, learn/self_hosted/install_meilisearch_locally.mdx
=> v1.10: Update Docker image tag

assets/misc/meilisearch-collection-postman.json
=> v1.10: Update Postman collection

.code-samples.meilisearch.yaml
Fixes #2961 
- Removes `limit` search parameter from queries in federated multi-search code sample
=> Remove limit from queries

learn/analytics/configure_analytics.mdx, learn/analytics/configure_monitoring.mdx, learn/experimental/vector_search.mdx, learn/filtering_and_sorting/filter_search_results.mdx, learn/relevancy/attribute_ranking_order.mdx, reference/api/documents.mdx
A recent update to the broken links checker revealed a few new outdated links. This PR fixes them.
=> Fix broken links

assets/misc/meilisearch-collection-postman.json
=> v1.11: Update Postman

guides/docker.mdx, learn/self_hosted/install_meilisearch_locally.mdx
=> v1.11: Update Docker image tags 

guides/running_production.mdx
=> Fix binary permission issues on run in production guide

config/redirects.json
=> Update redirects file

guides/docker.mdx, learn/self_hosted/install_meilisearch_locally.mdx
=> v1.12: Bump Docker image tag

reference/api/documents.mdx
=> Fix the edit document by filter route

reference/api/multi_search.mdx
Just stuff I stumbled across. Mostly copy&paste errors probably.
=> Fix some mistakes in federated multi search docs

reference/api/settings.mdx
fix likely copy/paste mistake. Reset Pagination (under Localized Attributes heading) should be "Reset localized attributes settings"
- fixes typo
=> fixed "Reset localized attributes settings" typo

reference/api/experimental_features.mdx
=> Update table of experimental features

reference/api/settings.mdx
- this is a type. all other `localizedAttributes` bodies show  ...{ "locales": [<String>] }...
=> typo - locale => locales

reference/api/settings.mdx
Specifically facet search and prefix search.
=> Fix incorrent "response" in settings

learn/configuration/configuring_index_settings_api.mdx, learn/filtering_and_sorting/search_with_facet_filters.mdx, learn/getting_started/primary_key.mdx, learn/self_hosted/getting_started_with_self_hosted_meilisearch.mdx, reference/api/documents.mdx, reference/api/facet_search.mdx, reference/api/keys.mdx, reference/api/multi_search.mdx, reference/api/search.mdx, reference/api/settings.mdx, reference/api/tasks.mdx
I was reading the Tasks reference, and noticed that a lot of the JSON blocks had some minor missing spaces. Next thing I know I have a vim macro in my hands and here we are.
Sorry if this is a waste of time. If this is superfluous (which it is) feel free to close the PR, no hard feelings :smile:
=> Add missing spacing in json blocks

learn/resources/comparison_to_alternatives.mdx
Fixes #3089
- Remove the maximum words per attribute line
=> Update comparison to alternatives

guides/docker.mdx, learn/self_hosted/install_meilisearch_locally.mdx
=> v1.13: Docker version bump

reference/api/stats.mdx
=> v1.13: Add new fields to `/stats` response

learn/self_hosted/configure_meilisearch_at_launch.mdx, learn/update_and_migration/updating.mdx
=> v1.13: Dumpless upgrades

assets/misc/meilisearch-collection-postman.json
=> v1.13: Update postman collection

learn/resources/comparison_to_alternatives.mdx
Fixes inaccuracies in comparison.
This PR: 
1. Fixes 2 inaccuracies on the comparison table concerning Elasticsearch license and embeddings.
2. Change a link to the Meilisearch monitoring documentation which is currently broken (404).
1. The license terms stated in the General Overview segment incorrectly state that Elasticsearch is SSPL licensed only. As of August 29th 2024, GNU Affero General Public License v3 (AGPL) was added as a license option for Elasticsearch and Kibana from v8.16 onwards. Please see the following [press release](https://ir.elastic.co/news/news-details/2024/Elastic-Announces-Open-Source-License-for-Elasticsearch-and-Kibana-Source-Code/default.aspx), [blog](https://www.elastic.co/blog/elasticsearch-is-open-source-again) and …
=> Corrections to Elasticsearch license and embedding info and broken Meilisearch URL

reference/api/overview.mdx
=> Fix OpenAPI heading level

learn/getting_started/cloud_quick_start.mdx, learn/resources/known_limitations.mdx
=> Add Cloud file upload size limitation

learn/relevancy/attribute_ranking_order.mdx
- Fix a typo in attribute_ranking_order.mdx: "claculating" -> "calculating"
=> Fix a typo in attribute_ranking_order.mdx

config/sidebar-guides.json, guides/ai/mcp.mdx
- Add a guide to connect Meilisearch with the MCP server & use it with Claude desktop
=> Add MCP server guide

learn/self_hosted/supported_os.mdx
=> v1.14: Update minimum linux glibc

reference/api/batches.mdx
=> v1.14: `/batches` response update

guides/docker.mdx, learn/self_hosted/install_meilisearch_locally.mdx
=> v1.14: Bump Docker version

assets/misc/meilisearch-collection-postman.json
=> v1.14: Update postman collection

guides/deployment/digitalocean.mdx, guides/docker.mdx, guides/front_end/search_bar_for_docs.mdx, guides/laravel_scout.mdx, guides/strapi_v4.mdx, home.mdx, learn/ai_powered_search/choose_an_embedder.mdx, learn/ai_powered_search/getting_started_with_ai_search.mdx, learn/ai_powered_search/retrieve_related_search_results.mdx, learn/analytics/configure_analytics.mdx, learn/analytics/configure_monitoring.mdx, learn/data_backup/dumps.mdx, learn/data_backup/snapshots.mdx, learn/data_backup/snapshots_vs_dumps.mdx, learn/engine/storage.mdx, learn/getting_started/cloud_quick_start.mdx, learn/self_hosted/configure_meilisearch_at_launch.mdx, learn/self_hosted/getting_started_with_self_hosted_meilisearch.mdx, learn/self_hosted/install_meilisearch_locally.mdx, learn/update_and_migration/migrating_cloud.mdx, learn/update_and_migration/updating.mdx, reference/api/dump.mdx, reference/api/search.mdx, reference/api/snapshots.mdx, snippets/samples/code_samples_getting_started_add_documents.mdx, snippets/samples/code_samples_getting_started_search.mdx
Assorted fixes for minor issues we noticed after migration.
=> Mintlify migration fixes bundle

docs.json
Previous PR caused the code samples bot to remove some java samples 🤷
=> Fixing redirects again

docs.json, meilisearch-search-bar.css, search.js, snippets/samples/code_samples_get_facet_search_settings_1.mdx, snippets/samples/code_samples_get_prefix_search_settings_1.mdx, snippets/samples/code_samples_getting_started_add_documents.mdx, snippets/samples/code_samples_reset_facet_search_settings_1.mdx, snippets/samples/code_samples_reset_prefix_search_settings_1.mdx, snippets/samples/code_samples_update_facet_search_settings_1.mdx, snippets/samples/code_samples_update_prefix_search_settings_1.mdx
=> Mintlify: Implement light mode and theme switcher

docs.json
=> Only use spaces for `docs.json` indentation

guides/docker.mdx, learn/self_hosted/install_meilisearch_locally.mdx
=> v1.15: Update Docker tags

guides/front_end/pagination.mdx, reference/api/settings.mdx
=> Increase `maxtotalhits` callout level to `Danger`

guides/docker.mdx, learn/self_hosted/install_meilisearch_locally.mdx, snippets/samples/code_samples_add_movies_json_1.mdx, snippets/samples/code_samples_add_or_replace_documents_1.mdx, snippets/samples/code_samples_add_or_update_documents_1.mdx, snippets/samples/code_samples_date_guide_filterable_attributes_1.mdx, snippets/samples/code_samples_date_guide_index_1.mdx, snippets/samples/code_samples_distinct_attribute_guide_filterable_1.mdx, snippets/samples/code_samples_facet_search_3.mdx, snippets/samples/code_samples_faceted_search_update_settings_1.mdx, snippets/samples/code_samples_filtering_update_settings_1.mdx, snippets/samples/code_samples_geosearch_guide_filter_settings_1.mdx, snippets/samples/code_samples_getting_started_add_documents.mdx, snippets/samples/code_samples_getting_started_add_meteorites.mdx, snippets/samples/code_samples_landing_getting_started_1.mdx, snippets/samples/code_samples_primary_field_guide_add_document_primary_key.mdx, snippets/samples/code_samples_typo_tolerance_guide_5.mdx, snippets/samples/code_samples_update_filterable_attributes_1.mdx
=> v1.16: Bump Docker image tag version

docs.json, snippets/samples/code_samples_webhooks_delete_1.mdx, snippets/samples/code_samples_webhooks_get_1.mdx, snippets/samples/code_samples_webhooks_get_single_1.mdx, snippets/samples/code_samples_webhooks_patch_1.mdx, snippets/samples/code_samples_webhooks_post_1.mdx
- linear: https://linear.app/meilisearch/issue/EXP-229/update-menu-version-from-vxy-to-latest
=> Replace top menu's `vX.Y`  with `latest`

learn/filtering_and_sorting/filter_expression_reference.mdx, learn/resources/telemetry.mdx, snippets/samples/code_samples_search_parameter_reference_media_1.mdx
=> Add vector filters

learn/ai_powered_search/document_template_best_practices.mdx, snippets/samples/code_samples_network_get.mdx, snippets/samples/code_samples_network_patch_1.mdx, snippets/samples/code_samples_network_patch_2.mdx
Fixes #3346
- Adds section suggesting to use if guards in documentTemplate guide
=> Add section about using if guards in documentTemplate guide

docs.json, snippets/samples/code_samples_get_vector_store_settings_1.mdx, snippets/samples/code_samples_primary_field_guide_update_document_primary_key.mdx, snippets/samples/code_samples_reset_vector_store_settings_1.mdx, snippets/samples/code_samples_swap_indexes_2.mdx, snippets/samples/code_samples_typo_tolerance_guide_5.mdx, snippets/samples/code_samples_update_an_index_1.mdx, snippets/samples/code_samples_update_an_index_2.mdx, snippets/samples/code_samples_update_vector_store_settings_1.mdx
As instructed by analytics consultant.
=> Disable GA4

docs.json
Fixes EXP-492 EXP-495 EXP-497 EXP-498
=> Add redirects

.code-samples.meilisearch.yaml, reference/api/settings.mdx
=> Fix vector store update verb
