meilisearch/documentation

advanced_guides/binary.md
We should use the `<Content/>` thing you talked about in https://github.com/meilisearch/documentation/issues/62 when stable, and avoid these little inconsistencies :)
=> Update the installation script URL in the binary.md

advanced_guides/asynchronous_updates.md, getting_started/features.md, references/documents.md, references/indexes.md, references/settings.md, references/stop_words.md, references/synonyms.md
I changed the word `action` only in API references, but the term `action` is widely used in [asynchronous explanation](https://github.com/meilisearch/documentation/blob/master/advanced_guides/asynchronous_updates.md).
Can you tell me if I have to change this part as well?
=> Rename action into update

advanced_guides/binary.md, getting_started/download.md, getting_started/quickstart.md
Documentation for [meilisearch/Meilisearch#401](https://github.com/meilisearch/MeiliSearch/pull/401).
We should merge this only when the PR is merged in MeiliSearch repo.
=> Add heroku quickstart

references/stats.md
Does `GET /stats` still exists?
Fixes: meilisearch/MeiliSearch#423
=> Change get stats of an index route

advanced_guides/search_parameters.md, main_concepts/search.md, references/search.md
Removed all occurrences of searchableAttributes or how it was previously called: attributes to search in.
fixes: meilisearch/MeiliSearch#429
=> Removed all occurence of searchable attributes

main_concepts/documents.md, main_concepts/indexes.md
Fixes: meilisearch/MeiliSearch#416 :
* The document id must contain only A-Z a-z 0-0 and -_. This is to avoid encoding in the url path in the case of a multi-word id.
=> Update rules of identifier

.vuepress/config.js, README.md, getting_started/download.md, guides/README.md, guides/advanced_guides/binary.md, references/README.md, references/readme.md, tutorials/README.md, tutorials/cookbooks/README.md, tutorials/cookbooks/readme.md, tutorials/howtos/README.md, tutorials/howtos/readme.md
```
I really LOVE the new structure!! (The new Home page, the separated part between Guide/Api Reference/Tutorial...)
Some points:
The search bar in the middle of the navbar chocks me a lot. Is it possible to put it at the right?
At the end of the QuickStart, the user is not redirected to another part of our documentation. Maybe the Guide part is a good idea...?
In Guide -> Getting started -> Download and launch :
1) there is a dead link on option available and the tests didn't see it.
2) I think it could be better to put all the possibilities of download like in Advanced Guide -> Installation (but we should find a way to link both tables)
```
@curquiza 
The searchbar position will be changed when I change the searchbar.
The user is now redirected to the getting started which in turn …
=> Fix on new doc

references/documents.md
Previously `POST indexes/:index_uid/documents/delete`
Now `POST indexes/:index_uid/documents/batch-delete`
=> Document delete route changes

.vuepress/config.js, guides/advanced_guides/README.md, guides/advanced_guides/installation.md, guides/getting_started/quick_start_guide.md
- Removed debug cargo build
- Changed `binary` file name to `installation`.
- Changed links from Binary to Installation
- Added Env and CLI variable MEILI_ENV
- Added environments explanation at the end of the installation guide
=> Changes in installation guide

.vuepress/config.js, guides/advanced_guides/README.md
Change the order of the guides in `advanced guides` category.
In the navbar they are ordered by what I considered to be the most important guides to grasp the knowledge of MeiliSearch.
In the README file they are ordered by importance and by type (API customization or General knowledge)
=> Change advanced guides navbar order

guides/getting_started/quick_start_guide.md, guides/main_concepts/search.md
On basis of this comment 
> Some points:
> 
> talking about the web interface in the getting started is mandatory for me :) And it should be mentioned in guides/main_concept/search, or at least put a link to the advanced guide part talking about the web interface.
> there is an empty file web in guides/advanced_guides
from @curquiza 
And also on wording changes and overall update of the search guide.
=> Web interface mention and changed to search guide

guides/advanced_guides/search_parameters.md
I know this feels kind of drive-by, but I'm currently in the process of writing a simple Go client for Meili and noticed this was off.
=> Fix typo in search_parameters.md

.vuepress/components/ClientGlossary.vue, guides/introduction/quick_start_guide.md, guides/main_concepts/documents.md, guides/main_concepts/indexes.md, references/indexes.md
Because I could not add ClientOnly in the glossary component since the dom element `this.$el` became empty in the mounted() method, I created a middle-man component that wrapped the glossary.
=> REFACTO: Create middle-man component to make glossary Client Only

.vuepress/components/RouteHighlighter.vue
The route prop in highlightRoute component was declared inside the method prop. I put it back at the root of the prop object.
=> Place route prop back to the root of the prop object

guides/advanced_guides/search_parameters.md
Related issue: #19
* Only one parameter accepter
* Parameter should be URL-encoded
* Example with URL-encoded spaces added
=> Correct filter documentation

references/settings.md
The update settings example had `GET` as a method instead of `POST`
=> Fix mistake in method to update settings

guides/introduction/quick_start_guide.md, references/stats.md, references/stop_words.md, references/synonyms.md, references/updates.md
I noticed this issue when I was testing the documentation for the first time, the index starts with `movies` and it changes to `12345678` later. This PR fix this issue making everything use the index `movies`.
=> Replace 12345678 with the correct movies index

.github/workflows/check-links.yml, .github/workflows/check-style.yml, .github/workflows/gh-pages.yml
Since the github action `actions/setup-node@v1` regularly timeout ( multiple times in the last few months [[1]](https://github.com/actions/setup-node/issues/132)[[2]](https://github.com/nodejs/build/issues/1993))
> 15 min before timeout on this C/I
And since latest version of node is builtin with the [OS](https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md) our github actions uses (search for `Node` [here](https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md)):     
```yml
runs-on: ubuntu-18.04
```
I completely removed `actions/setup-node@v1` from our g/a. Which was really useful in the case you need a specific version of node. We do not need an older version of node and we should keep up with node latest …
=> Remove unecessary node download during github actions

guides/advanced_guides/search_parameters.md, references/search.md
New formatting
Changed:
`filters=<Attribute>:<String>`
to:
`filters=<Attribute>:<Value>`
=> Search parameters

references/search.md
documents the addition of `nbHits` and `exhaustiveNbHits` to search result.
Adds response documentation for search result
Changes the example for the search result response so it's clear that `nbHits` is not the number of result in the response.
=> search result nbHits

.eslintrc.js, .vuepress/config.js, .vuepress/scraper/config.json, .vuepress/theme/components/MeiliSearchBox.vue, .vuepress/theme/components/Navbar.vue, guides/advanced_guides/filtering.md, guides/advanced_guides/search_parameters.md, references/search.md
Prepare version for v0.10. 
MeiliSearch CHANGELOGS:
=> Prepare documentation for meilisearch v0.10

references/settings.md
It doesn't seem clear enough in the documentation that a `POST` request on `/indexes/:index_id/settings` lets the user **partially** update an index settings 
This paragraph proposes an alternative to using specific routes, which seems to be an architectural choice of MeiliSearch and should be documented :) Let me know what you think!
[to my understanding, usually a POST request requires the whole body and won't accept just a few parameters]
=> Clarify partial update of settings via POST request

package.json, yarn.lock
In an upgrade, [mermaid](https://mermaidjs.github.io/#/) went from version 8.4 to 8.5. The changes in this new release breaks ore implementation of our mermaid schema. 
This should be addressed at some point #314
=> Fix version of mermaid to non breaking one

.vuepress/config.js, resources/cookbooks/running_production.md
This is the Tutorial for running a MeiliSearch in production. Still needs to be checked by myself for grammar etc, checked by someone else for content validation / test, and finally go through some native English speaker for polishing purposes :)
=> Tutorial: MeiliSearch in production

resources/tutorials/running_production.md
Fixed typo in running_production tutorial
Systend => systemd
Close #353
=> Fixed typo in running_production tutorial

.vuepress/docs-scraper/docs-scraper.config.json
Goal: providing a simple file for the users who want to imitate our config or to try understanding the config file.
=> Simplify config file for docs-scraper by removing useless fields

guides/advanced_guides/distinct.md
Fixes an error in `distinct attribute` example in the documentation. Two documents have the same id. See #376 
Closes #376
=> fix: error in distinct attribute example

.vuepress/code-samples/sdks.json
The url to the yaml sample file was not changed upon merging. 
Fixing with this PR
=> change curl sample url

guides/advanced_guides/field_properties.md
Error in the documentation that said:
```
Therefore, if a field attribute is not in the displayed-attribute list, the field won't be added to the documents returned upon search. Nevertheless, the documents fetched using the GET /documents route will have those fields, this setting only affects the document hits upon search.
```
Which is not true. Changed to: 
```
Therefore, if a field attribute is not in the displayed-attribute list, the field won't be added to the returned documents.
```
Discussed in: meilisearch/MeiliSearch#717
=> Fields not in displayed attribute are never in returned documents

.vuepress/enhanceApp.js
All links `docs.meilisearch.com/errors` and `docs.meilisearch.com/errors/*` (`*` being every possible value) are redirected to the documentation landing page.
=> Redirection of errors links to docs landing

.vuepress/config.js, faq/faq.md, guides/advanced_guides/configuration.md, guides/advanced_guides/installation.md, guides/advanced_guides/web_interface.md, guides/introduction/quick_start_guide.md, guides/main_concepts/documents.md
- Enable max payload size override (meilisearch/MeiliSearch#684)
- Breaking on max payload size
Moves the command line options and environment variables to a dedicated `configuration` page instead of in the `installation` page.
Introduces the limit of 10 MB in the document guide
Introduces the command line option to change the limit of the upload payload size
=> Payload limit and configuration guide

.code-samples.meilisearch.yaml, .vuepress/config.js, .vuepress/public/sample-template.yaml, guides/advanced_guides/settings.md, references/accept_new_fields.md, references/attributes_for_faceting.md, references/displayed_attributes.md, references/distinct_attribute.md, references/ranking_rules.md, references/searchable_attributes.md, references/stop_words.md, references/synonyms.md
- `Settings Configuration` guide is now called `Settings` to avoid confusion with configuration guide
- Added information about attributes for faceting in the settings references (This has been added in the main branch `prepare-new-version` not on purpose)
- Created dedicated reference for attributes for faceting
- Added 3 new code samples in the curl sample file and the template file
=> Attributes for faceting sub route

guides/introduction/quick_start_guide.md
`uid` is not needed and adding uid will cause `UnhandledPromiseRejectionWarning`.
error detail
`UnhandledPromiseRejectionWarning: MeiliSearchApiError: Invalid JSON: invalid type: map, expected a string at line 1 column 7`
=> uid is not needed

.vuepress/config.js, package.json, yarn.lock
A bug only present on master crashes when going directly to the getting_started guide.
-> [https://docs.meilisearch.com/guides/introduction/quick_start_guide.html](https://docs.meilisearch.com/guides/introduction/quick_start_guide.html)
I could not reproduce this neither on local neither on netlify. I suppose it comes from the latest plugin which is the `lazy load`.
Only indication I have is `warning An error was encountered in plugin "img-lazy"` on build. 
I suppose this is at the origin of the bug. I will investigate more later but fixing the doc is the most important.
=> should fix getting started

.code-samples.meilisearch.yaml
Replaces `GET` with `POST` in examples for update `searchable-attributes`, `displayed-attributes`, and `accept-new-fields`
=> Fix API Examples for Settings API Documentation

guides/advanced_guides/installation.md, guides/introduction/quick_start_guide.md
Unclosed warning created bugs in tabulations.
Removed them completely.
=> Remove buggy warning in tabs

.vuepress/code-samples/sdks.json
Should not be merged until the code-samples file is merge on:
=> Add links to code-samples file for PHP, Go and Ruby

.vuepress/public/sample-template.yaml
This comment is already added in the code-samples file in the Ruby, PHP and Go packages according to @tpayet and @eskombro reviews
see: https://github.com/meilisearch/meilisearch-ruby/pull/61#discussion_r447045529
=> Add comment at the top of the code-samples file

.code-samples.meilisearch.yaml
I get a bad request when I include `--get`, which seems like it'd conflict with `-X POST` anyway.
```
$ curl -H "x-meili-api-key: redacted" -X POST 'http://meilisearch.meilisearch.svc.cluster.local:7700/indexes/audionotes/settings/attributes-for-faceting' --get --data '["podcast_id"]'
*   Trying 10.20.15.209...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x562c2ede8f50)
* Connected to meilisearch.meilisearch.svc.cluster.local (10.20.15.209) port 7700 (#0)
> POST /indexes/audionotes/settings/attributes-for-faceting?["podcast_id"] HTTP/1.1
> Host: meilisearch.meilisearch.svc.cluster.local:7700
> User-Agent: curl/7.64.0
> Accept: */*
> x-meili-api-key: redacted
> 
< HTTP/1.1 400 Bad Request
< content-length: 0
< date: Sat, 11 Jul 2020 04:33:51 GMT
< x-envoy-upstream-service-time: 0 …
```
=> update faceting configuration curl example

.code-samples.meilisearch.yaml, .github/workflows/gh-pages-scraping.yml, .vuepress/code-samples/render.js, .vuepress/code-samples/sdks.json, .vuepress/config.js, .vuepress/public/sample-template.yaml, errors.yaml, guides/advanced_guides/installation.md, guides/introduction/quick_start_guide.md, guides/main_concepts/relevancy.md, package.json, resources/sdks.md, yarn.lock
https://github.com/meilisearch/MeiliSearch/issues/683
=> Documentation for error codes

.vuepress/config.js, .vuepress/enhanceApp.js, .vuepress/error-pages/index.js
Two new links:
- `/errors-list`
- `/errors/:error_code`
I could not make `/errors` and `/errors/:error_code` because of vuepress buggy way to handle `additionalPages`.
`/errors-list` is not mandatory and can be removed.
Also `errors.yaml` is bound to be removed once #421 is merged.
=> Errors documentation

.github/workflows/gh-pages-scraping.yml
The v0.10.1 is compatible with MeiliSearch v0.12.0 (the current Droplet version) and the v0.13.0 (upgrade coming after this PR is merged).
=> Upgrade docs-scraper from v0.10.0 to v0.10.1

guides/advanced_guides/authentication.md
I didn't test this, but I am guessing the public key also allows access to `POST /indexes/:index_uid/search`
=> Update authentication documentation regarding public key routes

guides/advanced_guides/search_parameters.md, references/search.md, references/searchable_attributes.md
This PR includes :
Adding empty string as a default value for `q` in `references/search.md` and `advanced_guides/search_parameters.md`
Modifying all `[*]` to `["*"]` (as in default value for `attributesToRetrieve` for example)
Changing POST and GET default values on `references/search.md`, taking into example the ones in `advanced_guides/search_parameters.md`
Closes #539
=> Modification of the default values on advanced_guides/search_parameters.md and references/search.md and [*] -> ["*"]

.code-samples.meilisearch.yaml, .eslintrc.js, .vuepress/components/glossary.vue, .vuepress/config.js, .vuepress/public/postman/meilisearch-collection.json, errors.yaml, guides/advanced_guides/configuration.md, guides/advanced_guides/known_limitations.md, guides/advanced_guides/search_parameters.md, guides/main_concepts/documents.md, references/dump.md, references/search.md, references/searchable_attributes.md
What is new in the 10/2020 release and where is doc needed: 
- All routes in [API references](https://docs.meilisearch.com/references/)
- All CLI options in [configuration](https://docs.meilisearch.com/guides/advanced_guides/configuration.html)
- [2 new error codes](https://github.com/meilisearch/MeiliSearch/pull/887#discussion_r493656064) must be added to the [error yaml](https://github.com/meilisearch/documentation/blob/master/errors.yaml)
- Change information in [Api references](https://docs.meilisearch.com/references/search.html#search-in-an-index-with-post-route)
- Change information in [Search parameters](https://docs.meilisearch.com/guides/advanced_guides/search_parameters.html)
=> Prepare documentation for MeiliSearch 10/2020 release

.code-samples.meilisearch.yaml
The documentation shows the invalid path (404)`http://localhost:7700/indexes/movies/delete-batch` as example endpoint for the `delete-batch` operation. 
The correct endpoint should be `http://localhost:7700/indexes/movies/documents/delete-batch`
=> Fix endpoint of delete-batch example

.code-samples.meilisearch.yaml, guides/advanced_guides/faceted_search.md, guides/advanced_guides/search_parameters.md, guides/advanced_guides/settings.md, references/attributes_for_faceting.md, references/documents.md, references/settings.md
Every occurrence of the "genre" field inside the documentation has been replaced with `genres` (expect for some precise case where `genre` was specifically chosen). 
Code-samples had some example containing `"genre"` instead of `"genres"` this has been changed as well and should be changed in every code-sample out there.
=> Update "genre" field into "genres"

guides/advanced_guides/configuration.md
I typed the wrong value `Production` from this place in the documentation and got the following error message:
```
error: 'Production' isn't a valid value for '--env <env>'
[possible values: development, production]
Did you mean 'production'?
USAGE:
meilisearch --db-path <db-path> --dump-batch-size <dump-batch-size> --dumps-dir <dumps-dir> --env <env> --http-addr <http-addr> --http-payload-size-limit <http-payload-size-limit> --master-key <master-key> --max-mdb-size <max-mdb-size> --max-udb-size <max-udb-size> --no-analytics <no-analytics> --sentry-dsn <sentry-dsn> --snapshot-dir <snapshot-dir>
For more information try --help
```
=> Env needs to be lowercase

resources/sdks.md
According to the @fharper request that I approved 👍 
(I know, renaming the URL is not mandatory but is consistent 😇)
=> Rename meilisearch-digital-ocean into meilisearch-digitalocean

resources/howtos/digitalocean_droplet.md
Since v0.17.0, MeiliSearch DigitalOcean droplet won't show the front-end interface if the environment is set to production. The screenshot in the `how-to` guide is replaced by an example on calling the `/health` route.
=> Update DigitalOcean how-to after v0.17

guides/advanced_guides/configuration.md, guides/advanced_guides/known_limitations.md, guides/main_concepts/documents.md
References [Issue 1137](https://github.com/meilisearch/MeiliSearch/issues/1137) and [PR 1147](https://github.com/meilisearch/MeiliSearch/pull/1147)
Increasing the default payload size from 10mb to 100mb.
=> Updating the default max payload size from 10mb to 100mb

.code-samples.meilisearch.yaml, guides/advanced_guides/field_properties.md
Improve the example for searchable fields in field_properties.md.
Idea comes from @bidoubiwa in https://github.com/meilisearch/documentation/pull/652#discussion_r551434483_
=> Field prop code sample

guides/advanced_guides/field_properties.md, guides/main_concepts/relevancy.md, references/searchable_attributes.md
Attempt to improve the documentation around searchable attributes as requested in #580 . 
"Attribute Importance" renamed to "Attribute Ranking Order". Information removed from API References and Main Concepts and consolidated in /guides/advanced_guides/field_properties.md.
I'm still unclear on the meaning of the last paragraph of #580 . Does this mean that if you manually reorder your searchableAttributes list, then reset it, the reset list will maintain the order you set, adding in all other attributes (new or previously non-searchable) to the end of the list?
If so, then wouldn't "reset" be a misnomer? It would actually be keeping your order while restoring the behavior of automatically adding all attributes.
=> Searchable attributes

resources/about_storage.md
The example on the [About Storate](https://docs.meilisearch.com/resources/about_storage.html#measured-disk-usage) page could be much clearer in my opinion about how much RAM and disk space MeiliSearch actually uses.
This PR uses the example and explicitly says how much RAM and disk space was used for that data set, just in case someone didn't understand the difference between virtual memory size, private memory size, real memory size, LMDB, etc.
**Before merging**, please double-check that I used the correct numbers for RAM and disk space. I think they're right, but I'm not 100% sure.
Fixes https://github.com/meilisearch/documentation/issues/694
=> Clarify storage and memory requirements

yarn.lock
Oke! So this was a tricky one. 
- `axios` is used by `meilisearch` < v0.14
- `docs-searchbar.js` uses `meilisearch`. 
- Docs-searchbar >= v.1.1.8 [Upgraded to meilisearch](https://github.com/meilisearch/docs-searchbar.js/blob/v1.1.8/package.json) > v0.14
- Before that version, because it uses meilisearch < v0.14, it had axios as a dependency of a dependency
- `vuepress-plugin-meilisearch` uses docs-searchbar.js. It uses the last version of docs-searchbar.js `v1.1.10`. Which uses meilisearch    `v0.17.0` which do NOT use `axios`.
So the 1 million question. Why with the latest version of `vuepress-plugin-meilisearch` do we still have `axios` as a dependency of dependencies?
```
docs-searchbar.js@^1.1:
version "1.1.7" // Why is it still 1.1.7 ?
dependencies:
meilisearch "^0.12.0" // …
```
=> Remove axios vulnerability

.code-samples.meilisearch.yaml, .vuepress/components/glossary.vue, .vuepress/config.js, guides/introduction/README.md, guides/introduction/quick_start_guide.md, guides/main_concepts/indexes.md, references/documents.md
This is a draft for lazy index in getting started. 
Since this PR is waiting on meilisearch/integration-guides#48 it is but as a draft to ensure it will **not be merged**.
=> Lazy index getting started suggestion

.code-samples.meilisearch.yaml, .vuepress/components/glossary.vue, LICENSE, guides/advanced_guides/installation.md, guides/introduction/README.md, guides/introduction/quick_start_guide.md, guides/main_concepts/indexes.md, package.json, references/documents.md, yarn.lock
Add information on how to keep data between versions. 
Should it be named update or upgrade? @react-learner 
Partially fixes: #698
Fixes: https://github.com/meilisearch/documentation/issues/665
=> Update upgrading guide in installation

README.md
Crisp chatbox has been disabled on Documentation site (and also on homepage, I think). README should reflect that.
=> Remove reference to Crisp chatbox from README.md

.code-samples.meilisearch.yaml, create/faq.md, create/how_to/digitalocean_droplet.md, create/how_to/http2_ssl.md, create/how_to/meilisearch_react.md, create/how_to/running_production.md, create/how_to/search_bar_for_docs.md, learn/core_concepts/documents.md, learn/tutorials/getting_started.md, reference/features/configuration.md, reference/features/installation.md, reference/features/snapshots.md
Remove command prompt from bash code samples, separate input from server response.
Fixes #731 , fixes #723
=> Make code samples copy+paste friendly

.vuepress/styles/index.styl
Copy icons should not increase the size of the code blocks with this style :) 
Preview:
=> Fixes code copy position

learn/what_is_meilisearch/contact.md
we want to focus the support on Slack or GitHub Discussions
=> Remove email contact

learn/advanced/asynchronous_updates.md, learn/advanced/snapshots_vs_dumps.md, reference/api/updates.md
As stated in #765 , the current documentation is unclear on updates, particularly which fields may be contained in the response body when you make a call to GET updates. This PR attempts to improve that situation.
Fixes #765
=> Clarify Update fields

.vuepress/public/sample-template.yaml
The template file is used on the build to determine if samples are missing in the different SDK's. As this one is not needed anymore it should be removed!
=> Remove code-sample in template file

.vuepress/config.js, create/how_to/README.md, create/how_to/qovery.md, create/how_to/updating.md, learn/getting_started/README.md, learn/getting_started/installation.md, learn/getting_started/quick_start.md, reference/features/configuration.md, reference/features/field_properties.md
- Improve create/how_to UX: add categories to sidebar
- Add updating guide (/create/how_to/updating.md)
- Improve installation.md (see #712 )
Closes #346 
Closes #660
=> Improve How To section

create/how_to/aws.md
Since v0.20.0 health check response from `/health` route sends a `200 OK` response instead of `204 No content`
=> Update AWS how-to v0.20.0: health check 200

reference/features/settings.md
Hello @react-learner, here is a behavior we've found out with the core team about ranking rule. No user complained for the moment, but I think the documentation should be transparent about it 🙂
Sorry for my English, I hope this is understandable.
In other words: because of the bucket sort, if the users don't provide documents with the attribute that they filled in the ranking rules, the search engine cannot behave in a "logical" way. This can lead to some undefined behavior (from the user POV), that's why we recommend having documents containing the fields in the ranking rules.
=> Add information about ranking rules

create/how_to/digitalocean_droplet.md
[Not to merge until DO image is released]
When the DigitalOcean image for MeilISearch v0.20.0 is released, the user `meilisearch` for establishing an SSH connection is no longer available. This needs an update in the documentation. As ~long~ soon as this image is released, the docs need to be updated. This PR indicates the needed changes!
=> Update DigitalOcean how-to

.vuepress/config.js
This will probably remove fathom and Amplitude at the end. I would like to use Segment to send Events to Amplitude without the need to configure Amplitude manually. Today, we only have the number of visitors on amplitude and I would like to know how many people visit each page and the average durations on these pages.
=> Add segment analytics

create/how_to/updating.md, reference/api/version.md
Due to changes described in meilisearch/transplant#138 
See tracker: https://github.com/meilisearch/documentation/pull/924
=> Change buildDate to commitDate

.vuepress/styles/index.styl
I noticed a small “bug” when reading the documentation on my smol screen.
When you scroll to the right, the code copy button also scrolls:
It's ugly. With this fix the position of the button stays “fixed” to the bottom right of the screen:
---------------
This fix was made thanks to @lordteka
=> Fix the copy code button

.vuepress/styles/index.styl
The copy button inside a code block overlaps with text (see [here](https://deploy-preview-944--dreamy-wiles-8fd85b.netlify.app/reference/features/filtering.html#examples))
Adapt the position of the button in style. Note that I had to use a `!important` because we use the external library `vuepress-plugin-code-copy` and it's the only way to override the initial style of the button.
Go to http://localhost:8081/reference/features/filtering.html#examples and check the position of the button
Before: 
After:
=> Fix position of the copy button inside a code block

.vuepress/config.js, .vuepress/public/_redirects, create/README.md, learn/core_concepts/documents.md, learn/getting_started/whats_next.md, reference/README.md, reference/api/README.md, reference/open-api/README.md, resources/faq.md, resources/open-api-readme.md
Basically, this PR adds a dropdown menu (titled "Resources") in the top Navbar with links to our FAQ, OpenAPI page, and SDK repos. It also moves FAQ and OpenAPI from their previous locations into a new directory, `/resources`.
Fixes #857
=> Add 'Resources' dropdown menu to navbar

.code-samples.meilisearch.yaml, reference/api/search.md
I noticed we were using the same code samples for the GET search and the POST search. Because of that, the GET search was broken.
=> fix the code samples for the search

README.md
Downloading `node-sass` used by `vuepress-plugin-element-tabs` is not possible when your node version is bellow v15. 
To make it compatible with node v15 and v16 node-sass should be updated to version 6 in the vuepress plugin. Because of [this line](https://github.com/superbiger/vuepress-plugin-tabs/blob/96cf59b10ccc8d877e8ba854a051ab8645e2215b/package.json#L32) it will not upgrade to the next major version.
=> Add requirements for dev env

reference/features/README.md
First paragraph of the Feature Reference currently says: `Want to know something about MeiliSearch? Chances are high that it's written down here.`
Not sure what this adds. If I want to know about e.g. Core Concepts it's not actually in this section, so it's potentially misleading.
=> Remove initial paragraph from Feature Reference intro

create/how_to/meilisearch_react.md
The current example does not work with the latest version of the lib.
=> [react example] fix JS example: import Meilisearch requires {}

errors.yaml
Remove `invalid_facet`, `missing_header`, `search_error`, and `bad_parameter` from the docs error page. These are being removed as part of v0.21.
=> Remove errors for v0.21

reference/api/search.md, reference/features/search_parameters.md
Proposals:
1. each parameter's description begins by listing the parameter name, its expected value and default values;
2. move the general search parameters examples from the bottom of the page to just below the table of contents;
3. add a warning stating that parameters must be URL-encoded when using the GET endpoint directly without an SDK (information verified with @curquiza).
Missing:
1. standardize and simplify examples and returned values
_This PR is a duplicate of #1016. Changes have been moved here to simplify merging with v0.21._
=> Reference audit: search parameters

reference/features/configuration.md
Clarifies language around how to configure MeiliSearch with cli flags and env vars.
SSL options are still unclear. This will be addressed in a future PR.
Fixes #978.
Duplicate of #976 (PR couldn't be merged with my current permissions).
=> Feature reference config

learn/advanced/asynchronous_updates.md, reference/features/search_parameters.md
This PR:
All of these changes are applied to `learn/advanced/asynchronous_updates.md`. Link to the preview: https://deploy-preview-1046--distracted-wiles-3edfc5.netlify.app/learn/advanced/asynchronous_updates.html
_This PR also fixes two links missing file extensions in `reference/features/search_parameters.md`. This is not related to the PR itself, but was necessary to get netlify to generate the preview._
=> v0.21: Update asynchronous update page

reference/api/settings.md
=> v0.21: reset settings with `null`

reference/features/known_limitations.md
=> v0.21: update known limitations

create/how_to/updating.md, reference/api/dump.md, reference/features/configuration.md, reference/features/dumps.md
=> v0.21: Dumps

reference/api/searchable_attributes.md, reference/features/field_properties.md
Manual updates to `searchableAttributes` change the order of the returned documents' fields.
=> v0.21: searchable attributes

learn/core_concepts/documents.md, learn/getting_started/installation.md, reference/features/configuration.md, reference/features/known_limitations.md
Log level
Analytics
MAX_MDB_SIZE
HTTP-PAYLOAD-SIZE-LIMIT
=> v0.21: Update configuration options

.vuepress/public/_redirects, errors.yaml
As reported on meilisearch/MeiliSearch/issues/1648, old links pointing to `reference/features/filtering` do not work and lead the user to a 404.
The reason for this is that the current redirect rule sends users to the `/reference/api/filtering_and_faceted_search.html`  instead of `/reference/features/filtering_and_faceted_search.html`
=> Fix filtering/faceted search redirects

learn/core_concepts/relevancy.md
The default ranking rules were updated with the release of version [0.21.0](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.21.0)
=> Update default order of ranking rules

learn/what_is_meilisearch/telemetry.md, resources/faq.md
MeiliSearch no longer uses Sentry to collect usage data. 
According to `ack`, the telemetry page is the only remaining location where we still mention it.
=> v0.22: Sentry

reference/api/search.md
Hey guys, thank you for a really awesome project!
I noticed that the `sort` param is not present in the API reference for the [GET](https://docs.meilisearch.com/reference/api/search.html#query-parameters) and [POST](https://docs.meilisearch.com/reference/api/search.html#body) search routes. I eventually learned about the `sort` param from the `/references/features/search_parameters` page, but I think it would be great to have it under `/references/api/search` as well.
I honestly haven't checked if there is an existing PR/issue about this, so apologies if this is a duplicate. Feel free to close this if that's the case!
=> add sort param to GET and POST search routes

.vuepress/code-samples/sdks.json
A bit counter-intuitive, but `cURL` code samples are located in the `master`, not the `main` branch.
Fixes #1152.
=> ./vuepress/code-samples/sdks.json: fix path to cURL samples

reference/features/search_parameters.md
In v0.24, `attributesToHighlight` works on both string and numeric values.
This PR updates the text to reflect that change and generally tries to improve wording on this search parameter's reference.
=> V0.24: attributesToHighlight

.code-samples.meilisearch.yaml, .vuepress/public/sample-template.yaml, learn/getting_started/quick_start.md
Reverts meilisearch/documentation#1173
We have an unknown error causing this new code sample to not be found. In addition, it should perhaps be standardized with the other getting started code samples (use `127.0.0.1` instead of `localhost`; wrapped in three upticks and marked as bash).
We also still need to request the integrations team to create code samples in other languages for this. So let's take a little longer to work on this PR.
=> Revert "users should check the index status before they start searching"

.vuepress/code-samples/client.js, .vuepress/code-samples/components/codeSamples.vue, .vuepress/code-samples/render.js, .vuepress/code-samples/sdks.json, .vuepress/code-samples/store.js, package.json, yarn.lock
This PR adds a state manager that upon clicking on a different label in the code-samples tabs, stores the language.
On language update, all other code-samples are updated accordingly. 
Meaning that if I click on `ruby`, the `ruby` tabs becomes not only the active one in the tabs I'm using, but in all others across the documentation. 
**Additionally** The store manager stores the language inside the local storage. 
Meaning that if you reload the page, the `ruby` will still be the one active
=> Add state manager to store last active code language tab.

learn/what_is_meilisearch/telemetry.md
Updating the telemetry table to be up-to-date with https://github.com/meilisearch/specifications/pull/95.
=> Update telemetry table: q.avg_terms_number is renamed q.max_terms_number

.code-samples.meilisearch.yaml
For some reason this code sample uses double quotes in its header, where every other code sample on the site use single quotes, e.g. for the `Content-Type` field. It's also the only code sample on the site to use `--header` instead of `-H`. 
Of note, it is the only code sample on our site to demonstrate communicating w/ a protected instance using `X-Meili-API-Key`, so there may be a good reason for this distinction. I can't imagine what it would be though, so it's probably better to be consistent 👀
=> standardize authentication_header code sample

learn/getting_started/installation.md
⚠️ This PR should be merged as soon as possible since it's a fix due to a breaking change introduced in v0.24.0 we did not anticipate. The current docker command in the docs is indeed obsolete.
The changelogs of [v0.24.0](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.24.0) have been updated
Related issue: https://github.com/meilisearch/MeiliSearch/issues/1969
=> Fix docker installation command

learn/getting_started/installation.md
I rollback the change I did in this PR https://github.com/meilisearch/documentation/pull/1329
Why? Here is the story
- A [PR](https://github.com/meilisearch/MeiliSearch/pull/1759) regarding the dockerfile was accepted, merged, and released in v0.24.0
- I realized, after the v0.24.0 release, this change in the dockerfile impacted the `data.ms` path: for the docker users, the default path was `/home/meili` and not `/` anymore. So, this change impacted the documentation command as well.
- So I created this PR (https://github.com/meilisearch/documentation/pull/1329) to fix the v0.24.0 documentation
- Some weeks later, we realized this dockerfile PR introduced a bug for the Linux users in v0.24.0
- Many spent a lot of time to fix this, but without any success
- We decided to [rollback the …
=> Revert docker command

reference/api/keys.md
The param `/:key` is not necessary 🍕
=> Remove unnecessary param from the create key path

learn/what_is_meilisearch/comparison_to_alternatives.md
- virtual replicas allow for sorting without the surcharge of duplicating the records: https://www.algolia.com/doc/guides/managing-results/refine-results/sorting/in-depth/relevant-sort/#step-one---create-a-virtual-replica-index
- the default max document size is 100kb, but used to be smaller
=> docs(comparison): clarify some algolia points

learn/what_is_meilisearch/comparison_to_alternatives.md
Elasticsearch has a Rails integration, so we are updating the comparison table accordingly. Thanks @Mcdostone for spotting this error.
Fixes #1384
=> Update comparison table

.vuepress/config.js, resources/faq.md
Since [removing all site READMEs](github.com/meilisearch/documentation/issues/1293) may [take some more time](github.com/meilisearch/documentation/pull/1400), this PR bundles several non-invasive improvements to browsing experience, such as:
- Add sidebar to the FAQ (replaces table of contents)
- Change Learn and Reference navbar links to point to the quick start and API reference readme, respectively
- Switch the order of API references and feature references in the `/reference` sidebar
=> Improve browsing experience

.vuepress/config.js
Before, it was calling the old meilisearch droplet
=> Update config.js to take the right new Meilisearch (on the Cloud)

.vuepress/public/_redirects
Redirect from old authentication guide location to new security guide location.
We missed this one at the time 😞 Thanks for the reminder @bidoubiwa !
=> Add missing redirect

learn/getting_started/installation.md
closes #1390 
After a little bit of testing, I noticed no difference by compiling from the source.
So instead of updating that part, we decided to remove it entirely, you can see the discussion here: https://github.com/meilisearch/documentation/pull/1390#discussion_r791981840
=> Remove the compiling from the sources part

.vuepress/config-path-checker/find-and-check.js
`path` is the whole API dealing with resolving paths and not the path that raised the error. Changed the variable to correct one. It raised these errors for you @guimachiavelli 
```
Path in config.json file is missing a trailing slash: path: '/learn/configuration/instance_options' (/.../config.json:110:17)
Path in config.json file is missing a trailing slash: path: '/learn/configuration/settings' (...config.json:115:21)
```
I also changed the link to where the error is thrown. Not sure why it was config.json.
=> Fix config path checker error handler

learn/advanced/storage.md
A linked blog post about the LMDB memory usage redirects to a dead link, I would prefer that we link to the old version of it instead.
I remember a discussion we had about hosting our own version of the post on our blog but for now, it would be cool to just forward to Webarchive.
=> Use webarchive to link to the deleted LMDB blog post

.vuepress/config.js, .vuepress/public/_redirects, reference/README.md, reference/features/README.md
The feature reference is no more, long live the feature reference.
Closes #1435
=> Remove feature reference section

learn/advanced/snapshots.md
The web rendering https://docs.meilisearch.com/learn/advanced/snapshots.html auto-links out to a domain (data.ms in this case) that doesn't exist. The proposed change just makes the reference uniform and doesn't link out to a domain that could be potentially phishy in the future.
- [🚫] Does this PR fix an existing issue?
- [✅] Have you read the contributing guidelines?
- [✅] Have you made sure that the title is accurate and descriptive of the changes?
Thank you so much for contributing to Meilisearch! (thank you! <3)
=> Update snapshot documentation to use uniform linking

.vuepress/public/_redirects
The getting started `README.md` file was removed as part of #1280 , but we forgot to add a redirect for it.
This PR adds a redirect from `/learn/getting_started/` to the quick start. It also standardizes the column spacing in the `_redirects` file, and changes a previously added redirect (`/reference/features/` should not redirect to `/reference/`, but to `/reference/api/`).
=> Add redirect from old getting started readme

learn/getting_started/quick_start.md
I have made an edit to the warning I had made about using docker on mac and windows: you can get decent performances by having the mounted volumes be in the docker virtual machine.
=> errata: edit to docker warning

.vuepress/config.js, learn/configuration/instance_options.md
Some improvements to `/learn/configuration/instance_options.md` focused around making the page more accessible from the sidebar. Note that target branch is `v0.26--instance-options-new-flag-behavior`. 
Summary:
- Change sidebar name + H1 to "Configure Meilisearch at launch"
- Eliminate "Usage" section (fold into two previous sections)
- Rename "Configuring Meilisearch with command-line options" and "Configuring Meilisearch with environment variables" to just "Command-line options" and "Environment variables"
- Display all command line options in the sidebar
- All SSL options changed to H4s and grouped under new H3 "SSL options"
- "Options" H2 + table of contents removed
- Distinction between "General" and "Advanced" options removed
- Category name changed from "Options" to "All instance …
=> v0.26 instance options trim

learn/advanced/geosearch.md
Currently, the geosearch examples return nothing because there are no points in a 2km range around `45.4628328, 9.1076931`.
Points 1 and 2 are the two points we already have in Italy.
And I made the query from the point 3 (less than 2km from 1&2).
=> Update the geosearch examples

learn/getting_started/quick_start.md
Hey! I have updated the docker link on the quickstart documentation leads to a 404 page. I have updated it to https://hub.docker.com/r/getmeili/meilisearch/tags. Please Review my PR.
Thanks!
#1501
=> Fixed : The docker link on the quickstart documentation leads to a 404 page #1501

.vuepress/config.js, yarn.lock
When using multiple same headers for example: 
```
```
Markdown gives the possibility to do this `#usage -2` to go to the second part. 
Unfortunately this breaks with the `check-links` tests. 
My MVP solution was to add a `ignoreHashPath` as an option to ignore the failed check.
⚠️ Be aware that this make it not possibility to know that the link is breaking
=> Add an option in check-md to ignore some links with anchors

.code-samples.meilisearch.yaml, .vuepress/public/restaurants.json, learn/advanced/geosearch.md
#1491 identified a problem w/ the Geosearch examples (thank you @alallema and @irevoire ! 🔥 )
This PR should fix the problem, and hopefully make the guide easier to follow.
- Update longitude + latitude coordinates so examples work as intended
- Remove distracting examples (located outside of the example section)
- Condense "Usage" section
- Add `restaurants.json` as an easily downloadable file so that users don't have to create the file themselves
- Add warnings about adding values to `filterableAttributes` and `sortableAttributes` so users aren't surprised when copy-pasted commands fail
=> Update geosearch guide

learn/cookbooks/gcp.md
Update GCP deploy version to 25.2
Related to this [Slack community thread](https://meilicommunity.slack.com/archives/CP9DVS1RQ/p1645634376018779)
=> Update gcp link to v25.2

.vuepress/config.js, learn/advanced/indexation.md, learn/experimental/auto-batching.md, learn/experimental/overview.md
PR replacing #1475 , which was thoroughly mucked up by an ill-timed `pull` and `rebase`.
=> v0.26: auto-batching (take two)

learn/cookbooks/gcp.md
Updating the GCP URL on the deploy page for v0.26.0.
=> Update gcp link to v0.26.0

learn/what_is_meilisearch/telemetry.md
Change `--no-analytics=true` to `--no-analytics`. This is the correct usage of command-line flags post v0.26.
Thank you @alallema !
Closes #1536
=> Update telemetry guide: missed change from v0.26

.vuepress/config.js, .vuepress/error-pages/index.js, index.md, learn/cookbooks/aws.md, learn/cookbooks/qovery.md, learn/what_is_meilisearch/features.md
- Rename the missing `MeiliSearch` into `Meilisearch` or `meilisearch`, depending on the case
- Also, fix typo on GitLab and GitHub
=> Remove the remaining MeiliSearch

learn/advanced/indexation.md, learn/advanced/updating.md, learn/cookbooks/search_bar_for_docs.md, learn/core_concepts/relevancy.md, learn/what_is_meilisearch/features.md, reference/api/search.md
To remove this:
You should avoid calling page from your own documentation by using the `https://...` that finish by `.html`
Indeed, when the scraper does its job, it will consider two different links are present:
- `https://docs.meilisearch.com/learn/configuration/instance_options#database-path`
- `https://docs.meilisearch.com/learn/configuration/instance_options.html#database-path`
So, it will consider 2 different documents should be added to Meilisearch!
Also, I recommend avoiding merging PRs that let useless whitespaces at the end of lines, so that it prevents other people like me apply changes on their PR that are not directly related to the PR :)
You can set up your editor settings to avoid this kind of error: it will remove automatically the trailing whitespaces when you save your …
=> Update links to remove the duplication of links in the search bar

learn/advanced/snapshots.md
EDIT: just found its also mentioned in the CLI docs. https://docs.meilisearch.com/learn/configuration/instance_options.html#schedule-snapshot-creation
As tried on v0.26.1, '--schedule-snapshot' doesn't need '=true' & works fine without it.
If included, throws error on below cli features.
1] activating snapshots
2] define snapshots directory
3] define snapshots interval
=> update docs: '=true' value no longer required

learn/security/tenant_tokens.md
Fixes #1542 "Signing API Key for a Tenant Token must have the search action defined"
=> Explicitly state API keys must have access to search

learn/advanced/known_limitations.md
Update `learn/advanced/known_limitations.md` to a add size of numeric fields as mentioned [here](https://github.com/meilisearch/meilisearch/issues/2205#issuecomment-1060817510)
=> update known_limitations to add size of integer fields

learn/security/tenant_tokens.md
Better to link to the API key actions table than the search endpoint IMO.
=> Update links related to api key actions

reference/api/indexes.md, reference/api/tasks.md
As we are planning to remove the path variable tables from all API endpoints, and as there are now multiple objects with the `uid` field in Meilisearch, it makes sense to be more specific about which "type" of uid an endpoint is expecting.
=> Replace {uid} with {index_uid} or {task_uid} in API reference

.code-samples.meilisearch.yaml, learn/cookbooks/digitalocean_droplet.md, learn/cookbooks/gcp.md, learn/core_concepts/indexes.md, learn/getting_started/filtering_and_sorting.md, learn/getting_started/quick_start.md, learn/what_is_meilisearch/search_preview.md, reference/api/documents.md, reference/api/indexes.md
closes #1596 
Example:
Update:
```
"uid":1,
```
to
```
"uid": 1,
```
=> update json responses to add space after `:` + fix typo

.github/workflows/gh-pages-scraping.yml, .vuepress/config.js, package.json, yarn.lock
- Update `vuepress-plugin-meilisearch` + `docs-scraper` to their latest versions
- Update Meilisearch host URL + API key for new Cloud instance (already created with the same stats)
=> Prepare to switch to new Cloud instance running Meilisearch v0.26

.code-samples.meilisearch.yaml, .vuepress/public/sample-template.yaml
The [Changing your primary key with the update index endpoint](https://docs.meilisearch.com/learn/core_concepts/primary_key.html#changing-your-primary-key-with-the-update-index-endpoint) code sample is not displaying because of different code sample ids
Rename  `primary_field_guide_update_primary_key` to `primary_field_guide_update_document_primary_key`
=> update primary key sample names

learn/core_concepts/relevancy.md
Default attribute ranking `searchableAttributes: ["*"]` is based on the order in which Meilisearch encounters attributes. This was clarified for me by https://github.com/meilisearch/specifications/pull/121/, line 316-317.
=> correct misunderstanding of default attribute ranking order

learn/getting_started/quick_start.md
This PR re-orders the cloud deploy options in the quick start, but its actual purpose is to re-trigger our build-deploy process and scraper.
The docs Meilisearch instance is currently returning a result belonging to a deleted page. This results in a 404 when the user clicks on it. To resolve this I first tried re-running the scraper, with no success. However this could be due to a problem w/ that specific branch, so I'm retrying with a fresh deploy.
=> Run CIs / fix scraper 404

.github/workflows/gh-pages-scraping.yml
Should fix scraping bug, but may cause problems since this version targets v0.27, and the docs instance is v0.26. Time will tell but it's worth a try!
=> Update docs scraper to v0.12.2

.code-samples.meilisearch.yaml, .vuepress/public/sample-template.yaml, learn/advanced/updating.md
[Step 2](https://docs.meilisearch.com/learn/advanced/updating.html#step-2-set-all-fields-as-displayed-attributes) of `/learn/advanced/updating.md` uses the wrong authorization header, it should be `  -H 'X-Meili-API-Key: apiKey'` instead of `  -H 'Authorization: Bearer apiKey'`
=> update authorization headers for updating.md

.vuepress/config.js, learn/getting_started/algolia_migration.md, learn/what_is_meilisearch/comparison_to_alternatives.md
@shivaylamba wrote an Algolia migration guide which I am now adapting for the docs.
Part 1: practical migration guide in Getting Started
- Migration script
- API comparison
- Settings + parameters comparison
- InstantSearch.js
To do:
Part 2: product comparison in Comparison to Alternatives
- Feature parity
- Pricing
To do:
=> Algolia migration guide

learn/getting_started/algolia_migration.md
The version of `meilisearch-js` is missing and impacts the code present in the guide a lot. 
To ensure the user install the correct version of the script I have added that specific version to the npm install command.
I also added some new lines where required (sorry for the out of subject action)
=> Add version of meilisearch-js in algolia migration guide

.vuepress/config-path-checker/README.md, .vuepress/config-path-checker/find-and-check.js, .vuepress/config-path-checker/index.js, .vuepress/config.js, .vuepress/public/_redirects
For some reason, since, we think, the introduction of this [PR](https://github.com/meilisearch/documentation/commit/09dedf36f14a4a019bacfce3029b577f4c637526) some pages were scraped two times by docs-scraper.
These pages have a pattern, these are always the parent of a sub menu with some child's on which it points: 
Example: 
https://github.com/meilisearch/documentation/blob/6687a450c5c3c46cf357bbf502854cd8c329423f/.vuepress/config.js#L143-L157
In these case, `/learn/configuration/settings.html` and `/learn/configuration/settings/` were considered as two different url's by the scraper and thus scraped two times (but not on every run..).
Resulting in situation like this one: 
**docs-scraper**
Because this behaviour is **flaky** we thought we might find a solution inside …
=> Fix duplicate scrapping of some nested pages

learn/getting_started/quick_start.md
I found one good practice about [docker here #6](https://developers.redhat.com/blog/2016/02/24/10-things-to-avoid-in-docker-containers) that mentions the usage of the latest tag. They don’t recommend it because it could be misleading and may not represent the actual state of the image throughout the days.
Since this could avoid some misleading problems for the users, the idea is to update the docs with the correct tag every time.
=> Apply the direct tag instead of latest alias

.github/workflows/check-links.yml, .github/workflows/gh-pages-scraping.yml, .vuepress/config.js, README.markdown, package.json, yarn.lock
fixes https://github.com/meilisearch/documentation/issues/1323
This PR becomes important as node 14 entered maintenance mode and will soon be EOL. Node 16 is now the current version and soon enough node 18 will takes its place. 
The documentation was not compatible with node 16 because it used [`vuepress-plugin-element-tabs`](https://github.com/Kaifun/vuepress-plugin-tabs) that itself used [`node-sass`](https://www.npmjs.com/package/node-sass) that is deprecated.
I created a fork of that same plugin [`@bidoubiwa/vuepress-plugin-elements-tabs`](https://github.com/bidoubiwa/vuepress-plugin-element-tabs) that upgraded `node-sass` to `sass`. Which makes it compatible with node 16. 
This PR also upgrades all `actions/setup-node` from v2 to v3 as v3 uses by default node v16.
A good …
=> Make documentation compatible with node 16

learn/core_concepts/documents.md
I was wanted to send a jsonlines file to meilisearch and noticed three things;
1. We never wrote the term `jsonlines` anywhere while it’s more commonly used than `ndjson`. So the search bar was returning nothing. Maybe we should also create a synonym that binds `jsonlines` to `ndjson`.
2. The example was wrong; as explained in the documentation, each JSON object should be on ONE line and thus can’t contain any newline.
3. We never tell the content type of each accepted type. So even once I found my answer, I still had to look up on google which header I was supposed to send to meilisearch to make it accept my document
=> Update the document structure to explicit the expected content-type

.code-samples.meilisearch.yaml, .vuepress/public/sample-template.yaml, learn/advanced/updating.md
Some code samples use the old `X-Meili-API-Key` header, to avoid confusion between an error and the fact that this header is used voluntarily it would be nice to add the suffix `old` at the end of the sample code name as it is already the case for some.
If you have a better idea I'm interested!
See with @dichotommy
=> Add `old` to the code sample name for old header

reference/api/documents.md, reference/api/dump.md, reference/api/health.md, reference/api/indexes.md, reference/api/keys.md, reference/api/settings.md, reference/api/tasks.md, reference/api/version.md
closes #1604 #1605
- Uses `/{routeName}` in API reference
=> update route format

learn/getting_started/quick_start.md
Users following the quick start sequentially will have problems with the current order, since the front-end integration code samples are not configured to work with a protected instance.
This is a temporary solution just for the weekend until we can add instructions on retrieving the search API key and incorporate that into the front-end code samples.
=> Move authorization after front-end in quick start

learn/getting_started/quick_start.md
Remove the word "vm" for https://github.com/meilisearch/documentation/pull/1646
=> remove `vm` from quick start

learn/configuration/synonyms.md, learn/configuration/typo_tolerance.md
As part of https://github.com/meilisearch/documentation/pull/1646, we want all words that are meant to be typos in backticks
=> Put all typos in backticks

learn/advanced/snapshots_vs_dumps.md
Update:
- `vs.` to `vs`
-  `snapshots` to `Snapshots`
for https://github.com/meilisearch/documentation/pull/1646
=> snapshots_vs_dumps.md

.code-samples.meilisearch.yaml, learn/advanced/updating.md, learn/cookbooks/search_bar_for_docs.md, learn/getting_started/quick_start.md, learn/security/master_api_keys.md, reference/api/keys.md
Replaces https://github.com/meilisearch/documentation/pull/1663
closes https://github.com/meilisearch/documentation/issues/1589
=> update masterKey/apiKey to MASTER_KEY/API_KEY

learn/getting_started/quick_start.md
In the command to start Meilisearch with Docker a backslash is missing in line 5.
=> Add backslash to Docker command in quick_start.

learn/getting_started/customizing_relevancy.md
just what the title says 👍🏻 
using the last sentence in the section solely to link to the next section is not a good look.
=> remove useless line from meilisearch 101

reference/api/search.md
This `q` parameter is obviously no longer optional, since the docs state what happens when it's not included:
> #Placeholder search
When q isn't specified, Meilisearch performs a placeholder search. A placeholder search returns all searchable documents in an index, modified by any search parameters used and sorted by that index's custom ranking rules...
=> Removed "mandatory" note for optional "q" search parameter

learn/getting_started/getting_ready_for_production.md
We don't want to encourage people to remove the telemetry. We want the transparency, but not encourage people to remove them when passing in production 😇
=> Remove information from "Getting ready for production" guide

learn/getting_started/quick_start.md
=> v0.28: Update Docker and Source tags

learn/advanced/geosearch.md
=> v0.28: accepted `_geo` `lat`, `lng` types

.code-samples.meilisearch.yaml, reference/api/displayed_attributes.md, reference/api/distinct_attribute.md, reference/api/filterable_attributes.md, reference/api/indexes.md, reference/api/ranking_rules.md, reference/api/searchable_attributes.md, reference/api/settings.md, reference/api/sortable_attributes.md, reference/api/stop_words.md, reference/api/synonyms.md, reference/api/typo_tolerance.md
=> v0.28: API endpoint verbs update

.code-samples.meilisearch.yaml, .vuepress/public/sample-template.yaml, learn/advanced/filtering_and_faceted_search.md, learn/configuration/distinct.md, learn/getting_started/algolia_migration.md, learn/getting_started/filtering_and_sorting.md, learn/getting_started/quick_start.md, reference/api/search.md
closes https://github.com/meilisearch/documentation/issues/1692
=> v0.28: /search name changes

.code-samples.meilisearch.yaml, .vuepress/public/postman/meilisearch-collection.json, reference/api/documents.md
=> v0.28: Changes to `/documents`

.code-samples.meilisearch.yaml, .vuepress/public/sample-template.yaml, learn/configuration/settings.md, learn/core_concepts/indexes.md
Adds faceting to:
- `/learn/configuration/settings.md`
- `/learn/core_concepts/indexes.md`
=> v0.28: Add faceting to core concepts+index settings

learn/what_is_meilisearch/telemetry.md
=> v0.28: Telemetry updates

.vuepress/config.js, learn/advanced/pagination.md
=> v0.28: Pagination guide

learn/advanced/tokenization.md, learn/what_is_meilisearch/language.md
Update language and tokenization pages for v0.28. Related to #1688
=> v0.28 hebrew tokenizer

learn/what_is_meilisearch/language.md
As requested on https://github.com/meilisearch/documentation/pull/1728#discussion_r915595694
=> v0.28: Update "create issue" link

learn/what_is_meilisearch/sdks.md
Firebase was listed as `SDK` while it is in fact a `platform plugin`
=> Change firebase integration to correct section

learn/advanced/asynchronous_operations.md
This type was removed in v0.28.0 release :)
ref: https://github.com/meilisearch/meilisearch/blob/de356061dbec1e5d7c38aeb0987c10ea6775de73/meilisearch-http/src/task.rs#L19
=> Remove task type's documentPartial value

.code-samples.meilisearch.yaml
This PR fixes two issues with code samples:
1. Code samples updating the global settings object in https://docs.meilisearch.com/learn/configuration/settings.html were using PUT instead of PATCH
2. The code sample updating the global settings object in https://docs.meilisearch.com/reference/api/settings.html#update-settings contained malformed data
Since these are errors specific to cURL, this PR should require no intervention by the integrations team.
=> Hotfix: global settings code samples

.vale.ini, .vale/styles/style_guide/SentenceLength.yml, learn/advanced/filtering_and_faceted_search.md, learn/advanced/geosearch.md, learn/core_concepts/primary_key.md, learn/what_is_meilisearch/comparison_to_alternatives.md
- Adds `SentenceLength.yml` to the style guide. This rule shows a warning if a sentence exceeds 40 words
- Updates any existing sentences with >40 words 
Most rules use a max of 25-30 words. Most of our “longer” (more than 25 words) sentences are between 27-30 words. The longest are ~42. We can start with 40 and bring it down
part of #1711
=> Vale: add sentence length rule

.vale/styles/style_guide/FirstPerson.yml
Updates the `FirstPerson.yml` message to: "Avoid first-person pronouns such as '%s' unless writing FAQs"
Unfortunately, we can't ignore this rule on some files like the FAQs, `learn/what_is_meilisearch/language.md`, etc., so we'll go with this for now. 
Part of https://github.com/meilisearch/documentation/issues/1711
=> vale: update firstperson.yml

learn/advanced/asynchronous_operations.md, reference/api/tasks.md
Part of #1351 
- Moved task filtering and pagination to the [async operations guide](https://docs.meilisearch.com/learn/advanced/asynchronous_operations.html)
- I think compared to the rest of the page, these headings are too technical? But that's something we can fix when we [rewrite the whole page ](https://github.com/meilisearch/documentation/issues/1273)
- Added `sidebarDepth: 2` so all subheadings are visible, especially under `Understanding tasks`
=> API reference: move task filtering and pagination to async guide

reference/api/tasks.md
Fixing `limit` and `from` values based on the code sample + response JSON
(These were updated recently in https://github.com/meilisearch/documentation/pull/1800 , but not accurately)
=> Update get tasks response

learn/advanced/dumps.md, reference/api/dump.md
part of #1351 
Updates:
- `/reference/api/dump.md`-> remove content to keep it short like the rest of the API reference pages
- `learn/advanced/dump.md`-> add content from `/reference/api/dump.md`
=> API reference: update dump.md

.vuepress/code-samples/components/codeSamples.vue
When a new code-sample-id is introduced but it has no code-sample associated to it in production the build crashes.
This is caused by a line on the code-sample rendering filters on all code-samples for a given code-sample-id to ensure non catchable tabs are defined. 
```js
this.ignoredTabs = CODE_SAMPLES[this.id].filter(tab => !tab.cacheableTab).map(tab => tab.label)
```
The filtering only works on arrays, but when a code-sample id had no associated code-sample, the filtering on an `undefined` value made the build crash.
=> Fix build crash when a case code-sample-id has no associated code-sample

reference/api/search.md
Fixed typo in Search Parameters type
Close https://github.com/meilisearch/documentation/issues/1882
=> Fix typo in Search API reference

learn/advanced/updating.md
It may not have been clear that this sentence only applies to Meilisearch versions < 0.21
=> Clarify some ambiguity in updating guide

learn/what_is_meilisearch/telemetry.md
=> V0.29: telemetry updates

reference/api/error_codes.md
Closes #1851 
This is not strictly necessary as we don't usually go into too much detail in the errors page, nor do we describe variant errors. 
Still, I took the update as an opportunity to add a bit more info to the description in hopes we can save users a click to the dedicated guide.
=> v0.29: Update `invalid_geo_field` error

.github/workflows/checks.yml, .github/workflows/deploy.yml, package.json
closes #1657 + removes support for node 12 + renames  `gh-pages-scarping.yml`(not very helpful) to `deploy.yml`
=> update node to ensure compatibility with node 16

learn/configuration/displayed_searchable_attributes.md, reference/api/search.md
closes #1256 
- Note vs warning. We agreed to use warnings when "missing the message could lead to really bad consequences". We won't have any bad consequences in this case, but users may not be aware of this so a warning sounds better
- I think a warning/note is enough to explain this behavior. But if we want to add code samples, we could add one to  `learn/configuration/displayed_searchable_attributes.md`. WDYT?
=> Highlight behavior regarding searchableAttributes

learn/getting_started/quick_start.md
The Quick Start page link to the wrong Docker Guide.
- Fix the link to use the existing guide
=> Fix the Docker guide link in the Quick Start documentation

.vuepress/config.js
Old placeholder text: "Search as you type..."
New placeholder text: "Type / to start searching"
Very open to feedback or suggestions if anyone sees any downsides with this approach.
=> Change search bar placeholder text

package.json, yarn.lock
This new version should fix the `flickering` issue when the searchbar renders see [this issue](https://github.com/meilisearch/vuepress-plugin-meilisearch/issues/263)
=> Upgrade vuepress-plugin-meilisearch to v0.12.4

learn/getting_started/quick_start.md
Syncs the versions with the docker pull and docker run commands to v0.29 in the quickstart guide. Otherwise, an error will be occur.
=> Sync versions with docker pull and docker run commands to v0.29

learn/advanced/working_with_dates.md
Missed a couple spots during our change from `year` to `release_date`.
Closes #1935
=> Working with dates guide: fix variable names

reference/api/settings.md
We have a note, tip, and warning at the beginning of the [stop words](https://docs.meilisearch.com/reference/api/settings.html#stop-words) section of the API reference. This PR merges the content of the note and tip to make it less overwhelming.
=> merge note and tip for stop words

package.json, yarn.lock
Upgrade version of vuepress-plugin-meilisearch that introduces the fix to the bad aligned logo on the right bottom corner of the popup.
before
after
=> Update vuepress-plugin-meilisearch to version v0.13.0

.github/workflows/checks.yml, learn/advanced/dumps.md, learn/advanced/snapshots.md, learn/configuration/instance_options.md
Closes #1965
Also updates the CLI flags warning box text since the difference between options available to CLI and env vars no longer exists.
=> v0.30: New environment variables

.github/workflows/checks.yml, learn/getting_started/quick_start.md
We received [feedback](https://meilisearch.slack.com/archives/C010VV3SHQF/p1668426724232999) (private link) from a user whose network security blocked all download requests except in-browser ones. This user couldn't figure out how to download Meilisearch based on the quick start docs.
This change should help users in similar situations.
=> Add direct download option to quick start installation section

learn/what_is_meilisearch/contact.md
#2010 
Updates contact page in light of discord migration. Removes outdated info.
=> Update contact page for Discord migration

learn/getting_started/quick_start.md
We don't use `stable` git branch anymore, but the `latest` git tag 😇
=> Use the new latest git tag instead of the stable branch

reference/api/indexes.md
Mistake in the `routeHighlighter` element for swap indexes; `/indexes` should not be part of the route.
=> No /indexes in swap-indexes endpoint route

reference/api/indexes.md
Payload format was incorrect, so I fixed it, and while I was at it cleaned up the explanation a bit.
=> Clarify swap indexes payload format

learn/advanced/dumps.md, learn/advanced/updating.md, learn/configuration/instance_options.md, reference/api/dump.md
Small, simple change to bring the `Dumps location` section of the instance options page closer to the name of the actual option (`dumps-dir`).
=> Make name of section similar to name of option

.vuepress/config.js, learn/advanced/updating.md, learn/what_is_meilisearch/comparison_to_alternatives.md
Note that I did not replace the "Public Slack community size" row in the comparison to alternatives. I think we should probably wait til our Discord server fills up a bit then change it to just say "Public community size" and replace the number.
=> Replace Slack links + mentions w/ discord

index.md, learn/what_is_meilisearch/comparison_to_alternatives.md
Replace all Meilisearch Cloud beta typeform links w/ links to the registration page.
=> Replace all Meilisearch Cloud beta typeform links

.vale/styles/style_guide/LatinTerms.yml
closes #1974 
Adds Vale rule to replace `i.e` and `e.g` with `that is` and `for example`, respectively. 
`that is` isn't the best replacement for `i.e`, but most style guides use it. I did add `consider rewriting the sentence` to the error message. Should we go with `meaning` instead?
=> add vale rule for latin terms

.github/workflows/checks.yml, reference/api/documents.md
closing #2014 
We updated the Vale action to use Vale 2.21.0 as the tests failed for Vale 2.21.1 (the latest version at the time of v0.30). It works with the latest version (2.21.3) now, so I'm removing that line
=> Update vale action

.code-samples.meilisearch.yaml, .vuepress/public/sample-template.yaml, learn/advanced/filtering_and_faceted_search.md, learn/advanced/sorting.md, reference/api/search.md
Closes #2035
Code samples are currently in code blocks to **_ease_** reviewing, but will be moved to `.code-samples.meilisearch.yaml` and `sample-template.yaml` after approval.
=> Add code samples for sorting/filtering nested fields

.code-samples.meilisearch.yaml
The `date_guide_index_1` code sample method flag is set as `post`, but it should be uppercased `POST`. 
https://github.com/meilisearch/documentation/blob/fc03ae707cb7890a0ce11be15165205234e26cee/.code-samples.meilisearch.yaml#L933-L937
=> Fix cURL code-sample where POST method was in lowercase

.vale.ini, .vale/styles/Meilisearch/British.yml, .vale/styles/Meilisearch/FirstPerson.yml, .vale/styles/Meilisearch/Headings.yml, .vale/styles/Meilisearch/Indexing.yml, .vale/styles/Meilisearch/LatinTerms.yml, .vale/styles/Meilisearch/MergeConflictMarkers.yml, .vale/styles/Meilisearch/OxfordComma.yml, .vale/styles/Meilisearch/Periods.yml, .vale/styles/Meilisearch/Repetition.yml, .vale/styles/Meilisearch/Semicolons.yml, .vale/styles/Meilisearch/SentenceLength.yml, .vale/styles/Meilisearch/Spacing.yml, .vale/styles/Meilisearch/Spelling.yml, .vale/styles/Meilisearch/Typos.yml, .vale/styles/Meilisearch/URLFormat.yml
Our style is currently called `style_guide`. This PR renames it to Meilisearch.
- Updates all rule files to rename the suggestion/warning/error from `style_guide.rule_name.yml` to `Meilisearch.rule_name.yml`
- Updates the style guide name in `vale.ini`
- Fixes typo in SentenceLength.yml
=> rename style guide to Meilisearch

learn/advanced/sorting.md
Mention that strings are sorted lexicographically based on their byte value
=> sorting accented characters

learn/configuration/instance_options.md
Improve organization of information concerning master key instance option
=> Clean up master key description in instance options page

.vuepress/enhanceApp.js
fixes: https://github.com/meilisearch/meilisearch/issues/3097
This PR ensures fixes the issue where the engine provides links with anchors containing underscores, whereas the doc are expecting hypens. Both type of anchors are now valid.
When an anchor is created for a heading in Vuepress all underscore are transformed to hypens.
For example:
```
```
Will have as anchor `#dump-not-found`.
Unfortunately, the meilisearch engine provides the links to the errors with underscores  (e.g. `"link": "https://docs.meilisearch.com/errors#index_not_found"`).
This PR adds a redirect on links to the errors references where an anchors has underscores (_) to the same URL but the underscores are transformed to hypens (-)
Example with the generated doc:
This …
=> Replace underscore with hypens in error_code anchor

learn/core_concepts/primary_key.md, reference/errors/error_codes.md
=> v1.0: Primary key inference

learn/advanced/known_limitations.md, reference/errors/error_codes.md
closes #2068 
Since users no longer get an `internal` error, I removed the "Large datasets and internal errors" limitation
=> v1.0: `too_many_open_files` error

learn/advanced/dumps.md, learn/advanced/updating.md
closes #2067
[This comment](https://github.com/meilisearch/meilisearch/issues/2985#issuecomment-1333840498) mentions some version-specific update FYIs that we can document. I added the first (`enqueued` updates are not exported) and last (DB creation date isn't exported) points. The other two seem too dump version specific. Please let me know if I should add them as well.
=> v1.0: remove two-step dump import process

learn/configuration/instance_options.md, learn/core_concepts/documents.md, learn/getting_started/quick_start.md, learn/what_is_meilisearch/telemetry.md, reference/api/documents.md
Closes #2085
Additionally, this PR also changes the wording of the `GET` documents endpoint so it doesn't use the word "batch" to keep our terminology consistent.
=> v1.0: Remove mentions of `--disable-auto-batching`

reference/api/tasks.md
=> v1.0: update to add  `*` for date filters in task api

learn/advanced/snapshots.md, learn/configuration/instance_options.md, learn/what_is_meilisearch/telemetry.md
=> v1.0: New snapshot scheduling behaviour

resources/faq.md
We found four old mentions reflecting our hopes and wishes for v1 around the documentation. Search was conducted using a grep-like tool with the following terms:
- `v1`
- `stable`
- `unstable`
- `in development`
- `major`
- `alpha`
- `beta`
Two mentions on the updating guide will be fixed by #2102.
This PR removes the remaining two mentions on the FAQ.
=> v1.0: remove stable v1 mentions

reference/api/documents.md
Hi team, my change is just to illustrate what I propose, but the correct way of explaining is up to you!
Since v1, when a user tries to run a `PUT indexes/my_index/documents` with a primary key, the task will fail and will not be silently ignored like it was in previous versions.
See:
```json
{
"uid": 3040,
"indexUid": "be566493",
"status": "failed",
"type": "documentAdditionOrUpdate",
"canceledBy": null,
"details": {
"receivedDocuments": 1,
"indexedDocuments": 0
},
"error": {
"message": "Index already has a primary key: `unique`.",
"code": "index_primary_key_already_exists",
"type": "invalid_request",
"link": "https://docs.meilisearch.com/errors#index_primary_key_already_exists"
},
"duration": "PT0.000590375S",
"enqueuedAt": "2023-02-06T01:50:52.315238299Z",
"startedAt": …
```
=> Clarify update documents with pk

learn/security/master_api_keys.md
N/A
The 'disabling security' section is no longer accurate in v1.0.0, following:
> As a security measure, Meilisearch will now reject master keys that are less than 16 bytes in [production environment](https://docs.meilisearch.com/learn/configuration/instance_options.html#environment) (https://github.com/meilisearch/meilisearch/pull/3274 and https://github.com/meilisearch/meilisearch/pull/3295)
```bash
$ docker run -it --rm -p 7700:7700 -e MEILI_ENV='production' -e MEILI_MASTER_KEY= -v $(pwd)/meili_data:/meili_data getmeili/meilisearch:v1.0
Error: The master key must be at least 16 bytes in a production environment. The provided key is only 0 bytes.
We generated a new secure master key for you (you can safely use this token):
>> --master-key JCXXid9dc52xJlGdzdw_krLhJ-uK6-ms9j5gDJoxAds << …
```
=> Remove disabling security

.github/CODEOWNERS
The idea is to use the [Github's CODEOWNERS feature](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) to help us the integrations team, track when the code-samples change.
⚠️ This is not a replacement for the work @maryamsulemani97 graciously does when she creates the issue listing all the changes, this is just a "plus" that will help us automatically review the changes we will implement in the SDKs and also help the docs team to understand if the sample is valid or not.
What happens when a PR with a code-sample change is submitted to the repository? The integration team should be automatically applied as a reviewer.
PS: The whole team should have access to "write" in the repository if you don't feel …
=> Add CODEOWNERS to .code-samples.meilisearch.yaml

learn/contributing/contributing_to_docs.md
Documentation team is an internal term. "Maintainer" is a more neutral term that is common in open-source communities. Right now, members of Meilisearch's documentation team are the only consistent maintainers of the Meilisearch documentation; however, we can imagine a future where some maintainers are not official employees.
=> Remove "documentation team" from contribution docs

.vuepress/code-samples/sdks.json
Vue3 code-sample was asked for and missing in the front-end integration samples. This PR add its.
⚠️ DO NOT MERGE before this PR is merged: https://github.com/meilisearch/meilisearch-vue/pull/121
=> Add vue3 code-sample

learn/what_is_meilisearch/language.md
It says Meilisearch uses four pipelines but counts five including the default one.
No issue created.
- Fix wrong information.
=> Fix pipeline count

learn/what_is_meilisearch/language.md
Fixes #2172
@ManyTheFish: do I understand correctly that Korean uses the default pipeline for space-separated languages? Or do we use another pipeline?
=> Add Korean to list of supported languages

learn/getting_started/supported_os.md
After discussing with @Kerollmops, we realized the current description of our OS support for Windows is not totally true (my bad). This PR fixes this
=> Make more accurate the Windows support

learn/what_is_meilisearch/language.md
Label was changed. This PR replaces outdated link for tokenizer feedback with a working one.
=> Fix link to product discussion in language.md

learn/getting_started/installation.md
use `${pwd}`  instead of  `$(pwd)` while  local installation in powershell 
- change command format for  local installation using docker  
=> change command format for powershell

reference/api/keys.md
=> v1.1: Use wildcard (`* `) when creating API keys

.code-samples.meilisearch.yaml, .vuepress/public/sample-template.yaml, learn/advanced/filtering_and_faceted_search.md, learn/advanced/geosearch.md, reference/api/search.md, reference/errors/error_codes.md
=> v1.1: Add new filter rule `_geoBoundingBox`

home.mdx
Trying to sketch what the new home would look like.
- Remove News section
- Remove most text
- Replace SDK reference `Capsule` content with Quick start link
- Replace placeholder `Featured` content with references to API reference, SDK page, Meilisearch Cloud, and blog
=> New site: Rough home draft

reference/api/multi_search.mdx
Using the term multi-index search implies that this route is meant to search on multiple indexes only. Which is not the case. This route is meant to perform multiple search on any index, may it be 4 times on the same index.
Also, the name of the route is multi-search and the feature is named multi search, it seems more consistent to keep that name.
=> Update the title Multi-index search in the api refs by removing index (on the new doc)

learn/update_and_migration/updating.mdx, reference/api/overview.mdx
This PR removes container titles and adds them to the container body for:
- `reference/api/overview.mdx`
- `learn/update_and_migration/updating.mdx`
=> Migration: remove note titles

home.mdx
When we write links in Markdown e.g. [link content](url), they are transformed at build so that /docs is added at the beginning—this gives us the correct site route.
However, when we write links in HTML/JS—like in component properties—they will not be transformed this way. In those cases, we have to remember the `/docs`
=> Fix homepage links in properties

config/sidebar-learn.json
update `docker` to `Docker` in the learn sidebar
=> Migration: update `docker` to `Docker` in the learn sidebar

home.mdx
Fixes homepage JSX syntax on `Featured` component.
_JSX should be always wrapped in only one tag (it can be an empty tag called "fragment"). We can use `()` for grouping it, `{}` means is a JS object so it won't work_
=> [FIX]: homepage JSX syntax

home.mdx
Remove "explore the docs" h2 from homepage because the spacing looks strange
=> Homepage remove explore the docs

learn/cookbooks/postman_collection.mdx
The link was not working in the tip title. This PR moves it to the tip body
=> Migration: update tip in postman guide

learn/advanced/faceted_search.mdx
Replaces vuepress containers with `<Capsule>`
=> Migration: replace vuepress containers from faceting guide

config/sidebar-learn.json
Some sections were using the same slugs, so the "Previous" and "Next" page links were incorrect. This PR assigns unique slugs to each section
=> Migration: update slugs in `config/sidebar-learn.json`

reference/api/search.mdx
Add `<br />` tags for line breaks between "Parameter", "Expected value", and "Default value" fields
=> Migration: Add `<br />` to search.mdx

resources/open-api-readme.mdx
This file contains links to the OpenAPI specifications. We have this links on the `/reference/overview` page
=> Migration: remove open-api-readme.mdx

learn/cookbooks/running_production.mdx
We no longer need it, as we have the On this page sidebar
=> Migration: remove toc from running_production.mdx

learn/cookbooks/search_bar_for_docs.mdx
closes #2283
This PR removes images and gifs using the old docs site
=> Migration: update search_bar_for_docs

config/sidebar-learn.json
Reverts meilisearch/documentation#2331|
Reverts changes to slugs in sidebar-learn.json as this breaks the redirects
=> Revert "Migration: update slugs in `config/sidebar-learn.json`"

learn/what_is_meilisearch/sdks.mdx
This page only had H3s, so nothing was showing up in the sidebar. At first I changed the `sidebarDepth`, but I think it makes more sense to follow best practices and switch to H2s.
=> Change SDK page from H3s to H2s

learn/advanced/faceted_search.mdx, learn/advanced/geosearch.mdx, learn/advanced/working_with_dates.mdx, learn/cookbooks/postman_collection.mdx, learn/cookbooks/search_bar_for_docs.mdx, learn/core_concepts/documents.mdx, learn/core_concepts/relevancy.mdx, learn/deployment/aws.mdx, learn/deployment/azure.mdx, learn/deployment/digitalocean.mdx, learn/deployment/gcp.mdx, learn/deployment/railway.mdx, learn/getting_started/quick_start.mdx, learn/meilisearch_101/filtering_and_sorting.mdx, learn/update_and_migration/updating.mdx, learn/what_is_meilisearch/overview.mdx, learn/what_is_meilisearch/search_preview.mdx
This PR updates all asset links from `https://raw.githubusercontent.com/meilisearch/documentation/new-docs-content-migration/assets/...` to `https://raw.githubusercontent.com/meilisearch/documentation/main/assets/...`
=> Migration: Update asset links

learn/core_concepts/documents.mdx
Auto-batching has been disabled temporarily for document addition and deletion tasks in v1.1.1. See https://github.com/meilisearch/meilisearch/pull/3667 for more details
=> v1.1.1:disable auto-batching

reference/api/multi_search.mdx, reference/api/settings.mdx
closes #2326 
This PR adds a warning that if one or more query/setting is badly formatted, or has a typo or error, Meilisearch will thrown an error. In case of multiple errors in the  query/setting, the error only addresses the first erroneous query/setting.
=> Add warning to settings and multi search API reference

config/sidebar-learn.json, learn/experimental/metrics.mdx, learn/experimental/reduce-indexing-memory-usage.mdx
Create page introducing `--experimental-reduce-indexing-memory-usage` to docs users and redirecting them to the feature discussion in the product repository for usage instructions.
Closes #2427
=> v1.2: New experimental instance option `--experimental-reduce-indexing-memory-usage`

reference/api/multi_search.mdx
Updates the multi-search API page to:
- Rename "POST route" to "Perform a multi-search"
- Add a description for the route 
Related to: https://github.com/meilisearch/documentation/pull/2370#issuecomment-1521539855
Added in https://github.com/meilisearch/meilisearch.com/pull/122
=> update multi-search API page

.code-samples.meilisearch.yaml
N/A
Added the missing backslash for the CURL command to check document status. Without this, user will get error: "authorization header is missing".
=> Add missing backlash in command for checking document status

learn/advanced/filtering.mdx, reference/api/search.mdx
This PR removes "```SQL" from filter expressions that aren't using SQL.
=> remove SQL from filter expressions

reference/api/multi_search.mdx
This PR updates `/reference/api/multi_search` to move the warning added in https://github.com/meilisearch/documentation/pull/2370 to the main endpoint description
=> Move warning in `multi-search.mdx` to main endpoint description

docs-scraper.config.json
Updates the `searchableAttributes` from `"*"` to:
-  "content" -> content in the docs. `null` for all heading levels
-  "hierarchy_lvl0" -> the section name
-  "hierarchy_lvl1" -> H1
-  "hierarchy_lvl2" -> H2
-  "hierarchy_lvl3" -> H3
-  "hierarchy_lvl4" -> H4
-  "hierarchy_lvl5" -> H5
=> update `searchableAttributes` in `docs-scraper.config.json`

config/sidebar-learn.json, learn/async/asynchronous_operations.mdx, learn/async/filtering_and_paginating_tasks.mdx, learn/async/managing_tasks.mdx, learn/data_backup/dumps.mdx, learn/getting_started/quick_start.mdx, learn/meilisearch_101/getting_ready_for_production.mdx, reference/api/dump.mdx, reference/api/indexes.mdx, reference/api/overview.mdx, reference/api/tasks.mdx, resources/faq.mdx
closes https://github.com/meilisearch/documentation/issues/2434
This PR:
- Adds a new section called "Tasks and asynchronous workflow" after the "Core concepts" section
- Adds two new pages to this section:
-  Asynchronous operations
- Filtering and paginating tasks
- Moves both pages to a new `async` folder under `learn`
Redirects added in: https://github.com/meilisearch/meilisearch.com/pull/130/files
=> Breakdown Advanced topics: Add Tasks and async workflow section

docs-scraper.config.json
This should fix the [failing scraper action](https://github.com/meilisearch/documentation/actions/runs/5257782790/jobs/9501194933#step:3:97) 🤞🏻
=> Remove trailing comma docs-scraper config

learn/core_concepts/relevancy.mdx
1. This PR removes the following headings from containers:
These headings appear in the sidebar when they shouldn't
2. Updates `Tabs.Container labels` to add "Exactness". The "Exactness" tab is currently missing from the container:
=> Update `relevancy.mdx` to remove h3s from containers+add missing tab

home.mdx, learn/getting_started/installation.mdx, learn/getting_started/quick_start.mdx, learn/what_is_meilisearch/comparison_to_alternatives.mdx
- make them traceable -> Objective 1 of Q3
- make them consistent: redirect to the pricing page and not the register one. The Cloud register page does not give any information and can be confused for the users
Discussed with @gmourier
=> Update links to Meilisearch Cloud

learn/inner_workings/known_limitations.mdx
closes https://github.com/meilisearch/documentation/issues/2488
Exceeding the document field limit will not impact anything, so we'll remove it from the docs
=> update known limitations

learn/cookbooks/postman_collection.mdx, learn/fine_tuning_results/faceted_search.mdx, learn/index_settings/distinct.mdx, learn/index_settings/synonyms.mdx, learn/index_settings/typo_tolerance.mdx, learn/inner_workings/prefix.mdx, learn/security/tenant_tokens.mdx
Part of https://github.com/meilisearch/documentation/issues/2377
This PR reduces containers from the `learn` section. It moves any content from the container that isn't important and adds it as regular text.
Closes #2474
=> Reduce containers

assets/misc/meilisearch-collection-postman.json
This PR updates `meilisearch-collection-postman.json` to add:
- New `facet-search` route
- Updates faceting settings route to add `sortFacetValuesBy`
- Adds new `showRankingScore` search parameter
=> v1.3: Update Postman for sort and search facets+showRankingScore

learn/async/managing_tasks.mdx, reference/api/tasks.mdx
=> v1.3: add `total` field to tasks response

learn/inner_workings/datatypes.mdx
In the example "Bruce Willis,Vin Diesel" there is not only a comma (8) but also a space (1) between Bruce and Vin, hence a distance of 9 instead of 8. Same applies to the subsequent examples in the following sentence. Otherwise it would be inconsistent with the next JSON example and the general concept of proximity outlined elsewhere in the documentation in which distances are plausibly characterized as additive.
=> Distance is the sum, not the max of distance values between words

learn/update_and_migration/algolia_migration.mdx
- Updates settings and parameters comparison in Algolia migration guide: adds `maxValuesPerFacet` and `sortFacetValuesBy`
=> Update settings and parameters comparison in Algolia migration guide

learn/cookbooks/vercel.mdx
- Adds tip about prefixing environment variables with [NEXT_PUBLIC_] for Next.js users
=> Add mention to env var prefix for Next.js users

learn/core_concepts/relevancy.mdx, learn/fine_tuning_results/sorting.mdx
=> Add link to document pinning blog posts

reference/api/documents.mdx, reference/api/facet_search.mdx
@bidoubiwa noticed we still have a few broken links our checker missed due to a typo in a few URLs pointing to the index settings API reference.
This PR fixes these broken links.
=> Fix broken links

config/sidebar-learn.json, learn/primary_db_sync/meilisync_mysql.mdx
Partially addresses #2542
Disclaimer for reviewers: I was not able to successfully install `meilisync` on my machine. I suspect it's related to some python misconfiguration on my end, but it became a huge time drain and I'm working on a short deadline for this. The guide might be rougher than usual because of that.
=> Meilisync MySQL guide

.code-samples.meilisearch.yaml
I created a quick script to check if all the [codes samples](https://github.com/meilisearch/documentation/blob/main/.code-samples.meilisearch.yaml) in this file are used in the official docs.
These ones are not
- `getting_started_communicating_with_a_protected_instance`
- `faceted_search_facets_1`
Since the integration team relies on this file, we need to keep it as up to date as needed to avoid additional work to the them 😊
=> Remove useless code samples

learn/cookbooks/docker.mdx, learn/getting_started/installation.mdx
=> v1.4: Docker version bump

learn/core_concepts/documents.mdx
Get rids of a warning on the autobatching of tasks not working with addition and deletions.
This has been fixed in https://github.com/meilisearch/meilisearch/pull/3670 a few months ago.
=> Remove warning on autobatching

config/sidebar-learn.json, learn/primary_db_sync/meilisync_mysql.mdx, learn/primary_db_sync/meilisync_postgresql.mdx
Partially addresses https://github.com/meilisearch/documentation/issues/2542
I adapted the MySQL guide to PostgreSQL by following the [guide](https://www.notion.so/meilisearch/Primary-DBs-with-Meilisearch-cf98503b6e6a40308f4e273ee828820e#106788f49fc740b7a9056ee49a61a3f4) written by @alallema.
🔗  [Preview](https://website-git-deploy-preview-mei-16-meili.vercel.app/docs/branch%3Ameilisync-postgresql/learn/cookbooks/meilisync_postgresql)
=> Add Meilisync PostgreSQL guide

learn/inner_workings/known_limitations.mdx
Following an internal discussion [here](https://meilisearch.slack.com/archives/C0557UPQHQA/p1695037338945139)
⚠️  review of @guimachiavelli mandatory before merging
=> Fix filter depth limitation

learn/deployment/railway.mdx
No open issue.  This change is being proposed because the template that is currently being deployed from the Deploy to Railway button on this page is not production ready - it does not have a volume attached meaning data will not be persisted between deploys, and the MEILI_ENV environment variable is set to development by default.
Update railway.mdx to point to a template that provides a production-ready instance of Meilisearch.  This Railways template includes default environment variables are production-ready and a volume attached for persisted data.
This change also updates the content to reflect that Meilisearch search preview is only available if you set your environment variable to "development" instead of the default "production"
Please check if your PR fulfills the following …
=> Update railway.mdx to reference production-ready Railway template

.github/dependabot.yml
Dependabot is not used anymore for npm since the website migration
I updated dependabot file to take care of github action dependencies only
We could also completely remove the file if you prefer @guimachiavelli
=> Update dependabot for GHA only

.github/workflows/preview-info.yml
Purpose: avoid this in the future => https://github.com/meilisearch/documentation/pull/2540#issuecomment-1705958900
=> Add GHA to add a comment displaying preview information on each opened PR

learn/experimental/overview.mdx, reference/api/experimental_features.mdx
=> v1.5: Activate `/metrics` via API route

learn/primary_db_sync/meilisync_mysql.mdx, learn/primary_db_sync/meilisync_postgresql.mdx
Fixes #2598 
- Add a notice about the field to configure the primary key for meilisync
=> Add notices about configuring Meilisync primary key

learn/what_is_meilisearch/sdks.mdx
- Change docs-searchbar.js description to deprecated following docs-searchbar.js repository
=> Change docs-searchbar.js description to deprecated

learn/index_settings/synonyms.mdx, reference/api/search.mdx
=> Keep info on phrase/placeholder search in a single place

learn/cloud/analytics.mdx
Fixes https://github.com/meilisearch/meilisearch/issues/4302
- Just fixing some code sample mistakes in the docs about the edge event handling!
=> Fix analytics events (CTR, conversion) instructions

config/sidebar-learn.json, learn/experimental/max_number_of_batched_tasks.mdx, learn/experimental/overview.mdx
=> v1.6: Limit task batch size

learn/experimental/vector_search.mdx
As reported on https://meilisearch.slack.com/archives/C063RND7214/p1705312242112009 (private link)
=> v1.6: Add instructions for disabling vector search

learn/cloud/analytics.mdx
Fixes https://github.com/meilisearch/meilisearch/issues/4309
This PR includes documentation for the `X-MS-USER-ID` header. This header allows to manually set the user id associated with a search and subsequent requests to the `/event` endpoint. Based on the [feedback of this issue](https://github.com/meilisearch/meilisearch/issues/4302#issuecomment-1885274716).
=> Meilisearch Cloud: Include documentation for custom user bindings

learn/fine_tuning_results/faceted_search.mdx, learn/fine_tuning_results/sorting.mdx, learn/security/tenant_tokens.mdx, learn/what_is_meilisearch/overview.mdx, reference/api/multi_search.mdx
- Add links to relevant demos on the screenshots
- Add links to the SaaS demo on those pages: tenant tokens, sorting, tenant tokens, multi-search API
- Add links to the Ecommerce demo on those pages: faceted search, sorting
=> Add contextual links to demos

learn/update_and_migration/updating.mdx
When importing the data during an upgrade and the instance has used different data and dump directories before, the import step also needs to use those or they will get created at the default location
Fixes #2701
- Clarifies the custom path parameters have to be added
=> Update updating.mdx respective custom data paths

learn/experimental/vector_search.mdx
As requested by @macraig, this PR adds a warning notifying Cloud users must enter the waitlist before activating vector search on Meilisearch Cloud.
=> v1.7: Vector search Cloud waitlist

.code-samples.meilisearch.yaml
`curl` code samples are not currently showing in the docs. I suspect this might be because of a formatting error in the code samples file
=> Fix code sample indentation

reference/api/overview.mdx
New file use for OpenAPI will be here: https://github.com/meilisearch/open-api/blob/main/open-api.yaml
We will stop to bump.sh soon -> too expensive, almost 2000$/year for no immediate impact
=> New usage of OpenAPI

learn/update_and_migration/updating.mdx
=> Review Meilisearch Cloud updating guide

docs-scraper.config.json
Scraper is failing because of parse error, there's trailing comma that should be removed.
=> Remove trailing comma

assets/misc/meilisearch-collection-postman.json
=> v1.8: Postman

reference/api/search.mdx
"Customize attributes to search on at search time" is not showing in the right sidebar  
[Webpage Link](https://www.meilisearch.com/docs/reference/api/search#customize-attributes-to-search-on-at-search-time)
Fixes #2827 
- removes the additional "#" which prevented the heading from showing in the right sidebar
=> attributesToSearchOn not showing in right sidebar

.code-samples.meilisearch.yaml, reference/api/search.mdx, reference/api/settings.mdx
This PR adds an initial base reference for:
- `hybrid` and `vector` search parameters
- `embedders` index setting
=> Vector search reference

learn/primary_db_sync/meilisync_postgresql.mdx
docker-compose is old and deprecated and now we should use "docker compose" instead.
- ...
- [y] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [y] Have you read the contributing guidelines?
- [y] Have you made sure that the title is accurate and descriptive of the changes?
=> replace the deprecated docker-compose

learn/primary_db_sync/meilisync_mysql.mdx
- docker-compose is deprecated and we should use "docker compose".
- [y ] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [y ] Have you read the contributing guidelines?
- [y ] Have you made sure that the title is accurate and descriptive of the changes?
=> replace deprecated docker-compose

config/sidebar-guides.json
Removes "deployment" guides that appear twice in the sidebar
=> Remove duplicate entries in guides sidebar

guides/running_production.mdx
Updated the useradd command to use the -s flag instead of -b when creating the meilisearch user
The flag for "/bin/false" should be "-s" , ensuring the user cannot log in.
=> changed useradd command flag '-b' to '-s'

learn/core_concepts/documents.mdx
- Fix typo of unique ID value to 1564, which should be equal to the id attribute in JSON example.
See https://github.com/meilisearch/documentation/blob/e426ed3ccf81694958f28610f76b734d3d4beb4a/learn/core_concepts/documents.mdx?plain=1#L94 for more.
=> Correct typo of unique ID value in Documents concept documentation

reference/api/search.mdx
This PR specifies that the `facetDistribution` is also exhaustive when using `page=0`.
=> The `facetDistribution` is also exhaustive when using `page=0`

learn/what_is_meilisearch/telemetry.mdx
=> v1.9: Telemetry

config/sidebar-guides.json, guides/front_end/vue_quick_start.mdx
- Adds Vue quick start 
- Creates the dedicated sidebar route in the frontend section of guides
=> Add Vue quickstart

guides/running_production.mdx
- It adds automatic restart to the systemd service template in the "Running in Production" section
The motivation is that if the service crashes (like from 6/ABRT errors during memory allocation, something I've seen several times during the last week) it should restart automatically and not stay dead until manual intervention.
- I set it to `Restart=always` because that is what I needed for my usage, but I know some maintainers prefer the more conservative `on-failure` or `on-abort` behavior. I can substitute that if you'd rather have that.
- The fix for the `too_many_open_files` error described in the [docs here](https://www.meilisearch.com/docs/reference/errors/error_codes#too_many_open_files) also requires a fix in this file, basically you have to set …
=> Update systemd service template

guides/database/meilisync_mysql.mdx, guides/database/meilisync_postgresql.mdx
After spending some time engaing with meilisync, it turns out that this project is still in a state of flux, lacking comprehensive testing and readiness for deployment in a live environment which is NOT suitable in the official document. I think it is necessary to address potential issues so that users could pay attention to this and make their own decisions.
=> Add "NOT PRODUCTION READY" disclaimer in syncing with meilisync chapters

learn/self_hosted/supported_os.mdx
We don't actually mention Ubuntu by its name, nor recommend a version, anywhere in the docs. Nothing to update there.
We do say Meilisearch self-hosted is compatible with any Linux machines with glibc 2.27, which this PR fixes.
Closes #2936.
=> v1.10: `glibc`version bump

learn/resources/telemetry.mdx
=> v1.10: Update telemetry table

.code-samples.meilisearch.yaml, reference/api/settings.mdx
`chi` does not work with Meilisaerch (`cmn` does)
But I removed it because we want to avoid users to set multiple languages: it will add a detection phase when indexing, so can lead to performance lost
=> Remove `chi` for `localizedAttributes`

.code-samples.meilisearch.yaml
Fixing wrong code sample namings following: https://github.com/meilisearch/documentation/pull/2950/files#diff-65d25ef75b16ef426e9e9d93d4ab97e174f75dd16ca8e4c0d7f4b7ca03173516
=> Fix language settings code samples

learn/resources/known_limitations.mdx
- Fix word order in [Maximum number of concurrent search requests](https://www.meilisearch.com/docs/learn/resources/known_limitations#maximum-number-of-concurrent-search-requests) section.
- Fix typo and update wording in [Facet Search limitation](https://www.meilisearch.com/docs/learn/resources/known_limitations#facet-search-limitation) section.
=> Fix typo in learn/resources/known_limitations

config/sidebar-guides.json, guides/embedders/cloudflare.mdx, guides/embedders/cohere.mdx, guides/embedders/mistral.mdx, guides/embedders/openai.mdx, guides/embedders/voyage.mdx
I created a first guide to use Mistral as an embedder in Meilisearch. Once this is confirmed I would be able to duplicate this content for all the embedders (OpenAI, Voyage, Cloudflare, and others).
=> Add a guides for generating embeddings with Mistral, OpenAI, Voyage, and Cloudflare

learn/ai_powered_search/getting_started_with_ai_search.mdx, learn/experimental/vector_search.mdx
I'm updating the UTMs parameters on links to:
- fix incorrect sources (should be: `utm_source=docs`)
- add `utm_medium` to help differentiate pages (will be more important with #2965)
=> feat: update UTM params on vector & hybrid search content

learn/self_hosted/configure_meilisearch_at_launch.mdx
Fix typo in task webhook authorization header reference 
Fixes #2949 
-Fix typo in task webhook authorization header reference  becuase of this typo mistake 
- changed `MEILI_TASK_AUTHORIZATION_HEADER` to `MEILI_TASK_WEBHOOK_AUTHORIZATION_HEADER`
=> Fix typo in task webhook authorization header reference

learn/resources/known_limitations.mdx
The limitation was slightly wrong, as you can see in meilisearch we keep a « safe margin of 32 bytes »:
https://github.com/meilisearch/meilisearch/blob/db0cf3b2ed0ca6cf6549510bf373681e83b775dd/milli/src/lib.rs#L106-L110
Discovered while trying to understand https://github.com/meilisearch/meilisearch/issues/4915
=> Fix the known limitation around the size of faceted values

.github/actions/validate-docs-links/src/checker.ts
Fixes #[NOT-78](https://linear.app/notum-meili/issue/NOT-78/docs-broken-links-checker-giving-false-positives-when-links-contain)
This PR fixes the issue where the link checker incorrectly flags valid links containing query parameters or hash anchors as broken.
1. **Query Parameters Handling:**
- Strips query parameters (e.g., `?utm_campaign=...`) from internal links before validation.
2. **Anchor Links Validation:**
- Ensures hash-based links (e.g., `#heading`) are correctly validated against document headings.
3. **No Changes to External or Static Asset Links:**
- External links and static assets continue to be ignored.
Previously, valid links with query parameters or hash fragments were incorrectly reported as broken. This fix improves the accuracy of the link checker.
- Links with …
=> fix: broken links in link checker

learn/getting_started/documents.mdx
=> Explicitly state attributes are case-sensitive

learn/engine/datatypes.mdx
Index name `movies_ratings` is not in the context of the filters in curl command, when there is filters with "appointments.date" and "appointments.doctor" and the results of patients
The index name `clinic_patients` would be much more relevant to this context
Fixes #2999 
- Replace `movies_ratings` to `clinic_patients` according to the context
=> Fix confusing index name

reference/api/multi_search.mdx, reference/errors/error_codes.mdx
=> v1.11: Federated search facets

learn/filtering_and_sorting/filter_expression_reference.mdx
=> v1.11: Add `STARTS WITH` to filter expression reference

.code-samples.meilisearch.yaml, reference/api/search.mdx, reference/api/settings.mdx
=> v1.11: Language settings

learn/indexing/indexing_best_practices.mdx, reference/api/settings.mdx
As discussed on [Slack](https://meilisearch.slack.com/archives/C07CLB9J4BH/p1728480901080119) (private link), we should provide clearer recommended usage guidelines for `binaryQuantized`.
=> v1.11: Binary quantization usage recommendation

config/sidebar-guides.json, guides/embedders/cloudflare.mdx, guides/embedders/huggingface.mdx
- Add a guide on how to use a model deployed on Hugging Face using Meilisearch rest embedder setting
- Fix a minor mistake in the Cloudflare one
=> Add Hugging Face Inference Endpoints as a rest embedder guide

learn/resources/known_limitations.mdx
The documentation currently informs users of limitations on the size of various data to 512 bytes, due to the maximum size of a LMDB key.
That maximum size is actually 511, as evidenced by https://github.com/meilisearch/meilisearch/issues/5050.
This documentation PR indicates the correct value for all involved values, while the companion code PR (https://github.com/meilisearch/meilisearch/pull/5144) replaces an internal error by a user error by checking against the correct value.
=> The max size of a key in LMDB is actually 511, not 512.

reference/api/tasks.mdx
Fixes #2818 
Currently [cancel tasks API reference](https://www.meilisearch.com/docs/reference/api/tasks#cancel-tasks) incorrectly mentions that even completed tasks can be cancelled. Updated the documentation to rectify that. Additionally added clarifications for which dates can be used for cancelling tasks.
Things to check:
1. Shouldn't we use the word **timestamp** instead of **date**? [`enqueuedAt`](https://www.meilisearch.com/docs/reference/api/tasks#enqueuedat) and [`startedAt`](https://www.meilisearch.com/docs/reference/api/tasks#startedat) are timestamps as per the documentation. Would writing it as timestamps contradict with the similar usage of dates everywhere else in the documentation?
2. Does the suggested change clearly convey the dates that can be used for task cancellation …
=> Updated cancel tasks API reference

assets/misc/meilisearch-collection-postman.json
=> v1.12: Update Postman collection

learn/resources/telemetry.mdx
=> v1.12: Update telemetry table

.code-samples.meilisearch.yaml, reference/api/settings.mdx, reference/errors/error_codes.mdx
=> v1.12: `prefixSearch` and `facetSearch` index settings

reference/api/settings.mdx
Currently, the examples are missing due to being referred to by the wrong names. See the correct names in [meilisearch-js](https://github.com/meilisearch/meilisearch-js/blob/896b5c0cf3479a04a1b137394796a5f34b161210/.code-samples.meilisearch.yaml#L802).
Links to the live site for convenience:
https://www.meilisearch.com/docs/reference/api/settings#example-19
https://www.meilisearch.com/docs/reference/api/settings#example-20
=> Correct example names for localizedAttributes

reference/api/search.mdx
Currently, the description of the `locales` search param does not make sense. When I read it it felt like a word was missing. Apologies if this was intended and correct.
In addition changed "language" to "language(s)" since more than one language may be specified.
=> Add missing word to desc of locales search param

reference/api/search.mdx
Fixes #3029
Added missing `distinct` param in search parameters overview table in `reference/api/search.mdx` file
Things to check:
1. Should the default value for `distinct` parameter be `null` or `""` empty string?
2. Is the description technically correct?  -> ` limit search to return one (most relevant) document per each value of specified attribute`
=> Added missing `distinct` param in search parameters overview

.code-samples.meilisearch.yaml
=> Use the PATCH /embedders path on update_embedders_1

reference/api/settings.mdx
There seems to be an issue in the documentation as it refers to  the `_vector` field instead of the `_vectors` one.
=> Update the embedder settings documentation

.code-samples.meilisearch.yaml, guides/computing_hugging_face_embeddings_gpu.mdx, guides/front_end/search_bar_for_docs.mdx, guides/improve_relevancy_large_documents.mdx, learn/ai_powered_search/deactivate_ai_powered_search.mdx, learn/ai_powered_search/getting_started_with_ai_search.mdx, learn/ai_powered_search/search_with_user_provided_embeddings.mdx, learn/async/task_webhook.mdx, learn/engine/datatypes.mdx, learn/filtering_and_sorting/filter_expression_reference.mdx, learn/multi_search/performing_federated_search.mdx, learn/security/generate_tenant_token_scratch.mdx, learn/security/generate_tenant_token_sdk.mdx, learn/security/generate_tenant_token_third_party.mdx, learn/update_and_migration/migrating_cloud.mdx, reference/api/documents.mdx, reference/api/logs.mdx, reference/api/metrics.mdx, reference/api/overview.mdx, reference/api/settings.mdx
Part of the continuous effort in rendering the docs less focussed on self-hosted instances.
@curquiza, this is the PR we spoke about changing all the target URL for all code samples. I'll only merge it after my return in the new year, so there's no rush as far as SDK code samples go. All changes relevant for the integrations team are in `.code-samples.meilisearch.yaml`—you can safely ignore the other 19 files touched by this PR.
=> Prefer `MEILISEARCH_URL` over `localhost:7700`

reference/api/search.mdx
Fixes #2774
Updated `expected values` for limit in `reference/api/search.mdx` file to include zero as a valid input to the limit parameter.
=> Updated `expected values` for limit in search.mdx

reference/errors/error_codes.mdx
It was linked before but did not exist. Copied word for word from tasks_not_found (with replacements of course), sorted alphabetically.
Fixes #3120
=> Add batch_not_found error code documentation

learn/data_backup/dumps.mdx
While this would be accurate if following the official instructions and running ./meilisearch right after downloading, there's nothing preventing someone from running the binary from a different directory.
=> Correct the location of the dumps folder

reference/api/overview.mdx
No standing issue
- simple fix of a typo in reference/api/overview.mdx
- fixed link - https://github.com/meilisearch/open-api/blob/main/open-api.yaml -> open-api.json
=> Fix typo - OpenAPI link reference(yaml -> json)

config/sidebar-learn.json, learn/ai_powered_search/choose_an_embedder.mdx
=> Add new article on how to choose embedder type

learn/ai_powered_search/getting_started_with_ai_search.mdx
This PR corrects the source key in the Meilisearch Getting Started guide, where the embedder source for OpenAI was incorrectly documented as `openai` instead of the correct `openAi`. Since embedder sources are case-sensitive, this fix ensures accuracy and prevents potential misconfigurations.
=> fix: case sensitivity

learn/self_hosted/configure_meilisearch_at_launch.mdx
Someone noticed that the env variable was not working when updating the logs mode, and that’s the fix 🌟 
Context: https://github.com/meilisearch/meilisearch/issues/5459
=> Update the env variable for the experimental logs mode

.code-samples.meilisearch.yaml, reference/api/settings.mdx
=> v1.14: New `filterableAttributes` format

reference/api/documents.mdx
=> v1.14: Get documents by `ids`

learn/resources/experimental_features_overview.mdx, reference/api/settings.mdx, reference/errors/error_codes.mdx
=> v1.14: Experimental feature: Composite embedders

reference/api/multi_search.mdx
=> Add missing search parameters to `/multi-search` reference

reference/api/multi_search.mdx, reference/api/search.mdx
Ensures all tables list the same parameters. Also removes one redundant table.
Fixes #2943
=> Simplify search parameter tables

.code-samples.meilisearch.yaml, learn/relevancy/typo_tolerance_settings.mdx, reference/api/settings.mdx
=> v1.15: Disable typo tolerance on numbers

reference/api/batches.mdx
=> v1.15: Add new `batchStrategy` field to batch object

learn/resources/experimental_features_overview.mdx, learn/self_hosted/configure_meilisearch_at_launch.mdx
=> v1.13: Experimental: Limit batch payload size

learn/resources/experimental_features_overview.mdx, learn/self_hosted/configure_meilisearch_at_launch.mdx
=> v1.15: Uncompressed snapshots

reference/api/facet_search.mdx
=> Remove misleading mention of `sortFacetValuesBy` from facet search reference

fathom-data-attr.js, snippets/samples/code_samples_update_filterable_attributes_1.mdx
Trying to patch fathom's script element with a data-attr to fix SPA tracking.
=> Patch fathom analytics

learn/resources/telemetry.mdx, snippets/samples/code_samples_add_movies_json_1.mdx, snippets/samples/code_samples_add_or_replace_documents_1.mdx, snippets/samples/code_samples_add_or_update_documents_1.mdx, snippets/samples/code_samples_date_guide_filterable_attributes_1.mdx, snippets/samples/code_samples_date_guide_index_1.mdx, snippets/samples/code_samples_distinct_attribute_guide_filterable_1.mdx, snippets/samples/code_samples_facet_search_3.mdx, snippets/samples/code_samples_faceted_search_update_settings_1.mdx, snippets/samples/code_samples_filtering_update_settings_1.mdx, snippets/samples/code_samples_geosearch_guide_filter_settings_1.mdx, snippets/samples/code_samples_getting_started_add_documents.mdx, snippets/samples/code_samples_getting_started_add_meteorites.mdx, snippets/samples/code_samples_landing_getting_started_1.mdx, snippets/samples/code_samples_primary_field_guide_add_document_primary_key.mdx, snippets/samples/code_samples_typo_tolerance_guide_5.mdx, snippets/samples/code_samples_update_filterable_attributes_1.mdx
=> v1.16: Telemetry updates

learn/filtering_and_sorting/filter_expression_reference.mdx
- linear: https://linear.app/meilisearch/issue/EXP-152/stabilize-starts-with
- engine: https://github.com/meilisearch/meilisearch/issues/5801
=> Remove experimental tags from STARTS WITH

learn/multi_search/implement_sharding.mdx, reference/api/network.mdx, reference/api/tasks.mdx, snippets/samples/code_samples_network_get.mdx, snippets/samples/code_samples_network_patch_1.mdx, snippets/samples/code_samples_network_patch_2.mdx, snippets/samples/code_samples_update_network_1.mdx
Fixes https://linear.app/meilisearch/issue/EXP-257/update-sharding-guide-following-splitting-of-documents (internal)
=> Update sharding documentation following Meilisearch's automatic splitting of documents

.code-samples.meilisearch.yaml, learn/resources/experimental_features_overview.mdx, reference/api/experimental_features.mdx, reference/api/settings.mdx, snippets/samples/code_samples_rename_an_index_1.mdx, snippets/samples/code_samples_search_parameter_reference_media_1.mdx, snippets/samples/code_samples_typo_tolerance_guide_5.mdx
=> Experimental feature: Vector store setting

.code-samples.meilisearch.yaml, learn/filtering_and_sorting/geosearch.mdx, reference/api/search.mdx, reference/errors/error_codes.mdx, snippets/samples/code_samples_facet_search_3.mdx, snippets/samples/code_samples_get_vector_store_settings_1.mdx, snippets/samples/code_samples_getting_started_add_documents.mdx, snippets/samples/code_samples_primary_field_guide_update_document_primary_key.mdx, snippets/samples/code_samples_ranking_score_threshold.mdx, snippets/samples/code_samples_rename_an_index_1.mdx, snippets/samples/code_samples_reset_vector_store_settings_1.mdx, snippets/samples/code_samples_swap_indexes_2.mdx, snippets/samples/code_samples_typo_tolerance_guide_5.mdx, snippets/samples/code_samples_update_an_index_1.mdx, snippets/samples/code_samples_update_an_index_2.mdx, snippets/samples/code_samples_update_vector_store_settings_1.mdx
=> Add  `_geoPolygon` and `_geojson` documentation
